project_id: "723773"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /docs/src/content/docs/**/*
    translation: /docs/src/content/docs/%two_letters_code%/**/%original_file_name%
    ignore:
      - /docs/src/content/docs/%two_letters_code%
