const AccessDenied: Int = 132; // Access denied — Thrown when the sender is not the owner of the contract. ownable.tact
const ContractStopped: Int = 133; // Contract stopped — Thrown when the contract has been halted and cannot process further messages. stoppable.tact
const InvalidArgument: Int = 134; // Invalid argument — Thrown when an invalid argument is passed to a function or method. text.tact
const ContractCodeNotFound: Int = 135; // Contract code not found — Thrown when the code for a contract is missing or cannot be located.
const InvalidStandardAddress: Int = 136; // Invalid standard address — Thrown when an address does not conform to the expected standard format. address.tact
