name: Other issue
description: Other issue (except security reports, please file those in private!)
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: other
    attributes:
      description: Compiler documentation, CI, testing, etc.
    validations:
      required: true
