contract ManyFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool;
    e: Int;
    f: Bool?;
    g: Int;
    h: Bool;
    i: Int?;
    j: Bool?;
    k: Int;
    l: Bool;
    m: Int?;
    n: Bool?;
    o: Int;
    p: Bool;
    q: Int?;
    r: Bool;
    s: Int?;
    t: Bool?;

    init() {
        self.a = 1;
        self.b = true;
        self.c = null;
        self.d = false;
        self.e = 2;
        self.f = true;
        self.g = 3;
        self.h = true;
        self.i = 9;
        self.j = null;
        self.k = 5;
        self.l = false;
        self.m = null;
        self.n = true;
        self.o = 10;
        self.p = false;
        self.q = -1;
        self.r = true;
        self.s = null;
        self.t = false;
    }
}