contract BoolArrayTest {
    b1: Bool = false;
    b2: Bool = false;
    b3: Bool = false;
    b4: Bool = false;
    b5: Bool = false;
    b6: Bool = false;
    b7: Bool = false;
    b8: Bool = false;
    b9: Bool = false;
    b10: Bool = false;

    init() {
        self.b1 = true;
        self.b2 = true;
        self.b3 = true;
        self.b4 = true;
        self.b5 = true;
        self.b6 = true;
        self.b7 = true;
        self.b8 = true;
        self.b9 = true;
        self.b10 = true;
    }

    receive() {}
}