contract BigFields {
    a0: Int = 0; a1: Int = 1; a2: Int = 2; a3: Int = 3; a4: Int = 4;
    a5: Int = 5; a6: Int = 6; a7: Int = 7; a8: Int = 8; a9: Int = 9;
    a10: Int = 10; a11: Int = 11; a12: Int = 12; a13: Int = 13; a14: Int = 14;
    a15: Int = 15; a16: Int = 16; a17: Int = 17; a18: Int = 18; a19: Int = 19;
    a20: Int = 20; a21: Int = 21; a22: Int = 22; a23: Int = 23; a24: Int = 24;
    a25: Int = 25; a26: Int = 26; a27: Int = 27; a28: Int = 28; a29: Int = 29;
    a30: Int = 30; a31: Int = 31; a32: Int = 32; a33: Int = 33; a34: Int = 34;
    a35: Int = 35; a36: Int = 36; a37: Int = 37; a38: Int = 38; a39: Int = 39;
    a40: Int = 40; a41: Int = 41; a42: Int = 42; a43: Int = 43; a44: Int = 44;
    a45: Int = 45; a46: Int = 46; a47: Int = 47; a48: Int = 48; a49: Int = 49;
    a50: Int = 50; a51: Int = 51; a52: Int = 52; a53: Int = 53; a54: Int = 54;
    a55: Int = 55; a56: Int = 56; a57: Int = 57; a58: Int = 58; a59: Int = 59;
    a60: Int = 60; a61: Int = 61; a62: Int = 62; a63: Int = 63; a64: Int = 64;
    a65: Int = 65; a66: Int = 66; a67: Int = 67; a68: Int = 68; a69: Int = 69;
    a70: Int = 70; a71: Int = 71; a72: Int = 72; a73: Int = 73; a74: Int = 74;
    a75: Int = 75; a76: Int = 76; a77: Int = 77; a78: Int = 78; a79: Int = 79;
    a80: Int = 80; a81: Int = 81; a82: Int = 82; a83: Int = 83; a84: Int = 84;
    a85: Int = 85; a86: Int = 86; a87: Int = 87; a88: Int = 88; a89: Int = 89;
    a90: Int = 90; a91: Int = 91; a92: Int = 92; a93: Int = 93; a94: Int = 94;
    a95: Int = 95; a96: Int = 96; a97: Int = 97; a98: Int = 98; a99: Int = 99;
}
