contract LongListOptionals {
    o1: Int? = null;
    o2: Bool? = null;
    o3: Int? = null;
    o4: Bool? = null;
    o5: Int? = null;
    o6: Bool? = null;
    o7: Int? = null;
    o8: Bool? = null;
    o9: Int? = null;
    o10: Bool? = null;
    init() {
        self.o1 = null; self.o2 = null; self.o3 = null; self.o4 = null;
        self.o5 = null; self.o6 = null; self.o7 = null; self.o8 = null;
        self.o9 = null; self.o10 = null;
    }
}