contract LotsOfFields {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Int;
    f: Int;
    g: Int;
    h: Bool;
    i: Bool;
    j: Bool;
    k: Bool;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = 4;
        self.e = 5;
        self.f = 6;
        self.g = 7;
        self.h = true;
        self.i = false;
        self.j = true;
        self.k = false;
    }
}