contract ManyFields {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int?;
    f5: Bool?;
    f6: String?;
    f7: Int;
    f8: Bool;
    f9: String;
    f10: Int?;
    f11: Bool?;
    f12: String?;

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = "3";
        self.f4 = null;
        self.f5 = false;
        self.f6 = "6";
        self.f7 = 7;
        self.f8 = false;
        self.f9 = "9";
        self.f10 = 10;
        self.f11 = null;
        self.f12 = null;
    }
}
