contract Test15 {
    f1: Int?;
    f2: Int?;
    f3: Int?;
    f4: Int?;
    f5: Int?;
    f6: Int?;
    f7: Int?;
    f8: Int?;
    f9: Int?;
    f10: Int?;

    init() {
        self.f1 = null;
        self.f2 = 2;
        self.f3 = null;
        self.f4 = 4;
        self.f5 = null;
        self.f6 = 6;
        self.f7 = null;
        self.f8 = 8;
        self.f9 = null;
        self.f10 = 10;
    }
}