contract LongIntList {
    i1: Int = 1;
    i2: Int = 2;
    i3: Int = 3;
    i4: Int = 4;
    i5: Int = 5;
    i6: Int = 6;
    i7: Int = 7;
    i8: Int = 8;
    i9: Int = 9;
    i10: Int = 10;
    i11: Int = 11;
    i12: Int = 12;
    i13: Int = 13;
    i14: Int = 14;
    i15: Int = 15;
    i16: Int = 16;
    i17: Int = 17;
    i18: Int = 18;
    i19: Int = 19;
    i20: Int = 20;
    i21: Int = 21;
    i22: Int = 22;
    i23: Int = 23;
    i24: Int = 24;
    i25: Int = 25;
    i26: Int = 26;
    i27: Int = 27;
    i28: Int = 28;
    i29: Int = 29;
    i30: Int = 30;
    receive() {}
}
