contract TestContract {
    int1: Int = 1;
    int2: Int = 2;
    int3: Int = 3;
    int4: Int = 4;
    int5: Int = 5;
    int6: Int = 6;
    int7: Int = 7;
    int8: Int = 8;
    int9: Int = 9;
    int10: Int = 10;
    int11: Int = 11;
    int12: Int = 12;
    int13: Int = 13;
    int14: Int = 14;
    int15: Int = 15;
    int16: Int = 16;

    init() {
        self.int1 = 1;
        self.int2 = 2;
        self.int3 = 3;
        self.int4 = 4;
        self.int5 = 5;
        self.int6 = 6;
        self.int7 = 7;
        self.int8 = 8;
        self.int9 = 9;
        self.int10 = 10;
        self.int11 = 11;
        self.int12 = 12;
        self.int13 = 13;
        self.int14 = 14;
        self.int15 = 15;
        self.int16 = 16;
    }
}
