struct BigData {
    a: Int = 1;
    b: Bool = false;
    c: String = "x";
    d: Int = 2;
    e: Bool = true;
    f: String = "y";
    g: Int = 3;
    h: Bool = false;
    i: String = "z";
    j: Int = 4;
    k: Bool = true;
    l: String = "w";
    m: Int = 5;
    n: Bool = false;
    o: String = "v";
    p: Int = 6;
    q: Bool = true;
    r: String = "u";
    s: Int = 7;
    t: Bool = false;
    u: String = "t";
}
contract LargeNested {
    dat: BigData = BigData{};
    init() {}
}