contract LotsOptional {
  a: Int?; b: Int?; c: Int?; d: Int?; e: Int?;
  f: Bool?; g: Bool?; h: Bool?; i: Bool?; j: Bool?;
  s: String?; t: String?; u: String?; v: String?; w: String?;

  init() {
    self.a=null; self.b=null; self.c=null; self.d=null; self.e=null;
    self.f=null; self.g=null; self.h=null; self.i=null; self.j=null;
    self.s=null; self.t=null; self.u=null; self.v=null; self.w=null;
  }
}