contract TwentyFields {
    f01: Int = 1;
    f02: Int = 2;
    f03: Int = 3;
    f04: Int = 4;
    f05: Int = 5;
    f06: Int = 6;
    f07: Int =7;
    f08: Int =8;
    f09: Int =9;
    f10: Int=10;
    f11:Int=11;
    f12:Int=12;
    f13:Int=13;
    f14:Int=14;
    f15:Int=15;
    f16:Int=16;
    f17:Int=17;
    f18:Int=18;
    f19:Int=19;
    f20:Int=20;

    init() {
        self.f01=0; self.f02=0; self.f03=0; self.f04=0; self.f05=0;
        self.f06=0; self.f07=0; self.f08=0; self.f09=0; self.f10=0;
        self.f11=0; self.f12=0; self.f13=0; self.f14=0; self.f15=0;
        self.f16=0; self.f17=0; self.f18=0; self.f19=0; self.f20=0;
    }
}