contract LotsOfOptionals {
    f1: Int?;
    f2: Int?;
    f3: Int?;
    f4: Bool?;
    f5: Bool?;
    f6: String?;
    f7: String?;
    f8: Address?;
    f9: Address?;
    f10: Cell?;
    f11: Slice?;

    init() {
        self.f1 = null;
        self.f2 = null;
        self.f3 = null;
        self.f4 = null;
        self.f5 = null;
        self.f6 = null;
        self.f7 = null;
        self.f8 = null;
        self.f9 = null;
        self.f10 = null;
        self.f11 = null;
    }
}