contract OptionalMany {
    o1: Int?;
    o2: Int?;
    o3: Int?;
    o4: Bool?;
    o5: Bool?;
    o6: String?;
    o7: String?;
    o8: Address?;
    o9: Cell?;
    o10: Slice?;

    init() {
        self.o1 = null;
        self.o2 = null;
        self.o3 = null;
        self.o4 = null;
        self.o5 = null;
        self.o6 = null;
        self.o7 = null;
        self.o8 = null;
        self.o9 = null;
        self.o10 = null;
    }
}