contract LargePlain {
    a: Int;
    b: Bool;
    c: String;
    d: Int;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int;
    k: Bool;
    l: String;

    init() {
        self.a = 1;
        self.b = true;
        self.c = "a";
        self.d = 2;
        self.e = false;
        self.f = "b";
        self.g = 3;
        self.h = true;
        self.i = "c";
        self.j = 4;
        self.k = false;
        self.l = "d";
    }
}