contract LargeContract {
    f1: Int;
    f2: Int?;
    f3: String;
    f4: String?;
    f5: Bool;
    f6: Bool?;
    f7: Int;
    f8: Int?;
    f9: String;
    f10: String?;
    f11: Bool;
    f12: Bool?;
    f13: Int;
    f14: Int?;
    f15: String;
    f16: String?;
    f17: Bool;
    f18: Bool?;

    init() {
        self.f1=1; self.f2=2; self.f3="a"; self.f4=null;
        self.f5=true; self.f6=false; self.f7=7; self.f8=8;
        self.f9="b"; self.f10=null; self.f11=false; self.f12=null;
        self.f13=13; self.f14=14; self.f15="c"; self.f16=null;
        self.f17=true; self.f18=null;
    }
}