contract OptionalLong {
    a1: Int?;
    a2: Int?;
    a3: Int?;
    a4: Int?;
    a5: Int?;
    a6: Int?;
    a7: Int?;
    a8: Int?;
    a9: Int?;
    a10: Int?;
    a11: Int?;
    a12: Int?;
    a13: Int?;
    a14: Int?;
    a15: Int?;
    a16: Int?;
    a17: Int?;
    a18: Int?;
    a19: Int?;
    a20: Int?;

    init() {
        self.a1=null;self.a2=null;self.a3=null;self.a4=null;
        self.a5=null;self.a6=null;self.a7=null;self.a8=null;
        self.a9=null;self.a10=null;self.a11=null;self.a12=null;
        self.a13=null;self.a14=null;self.a15=null;self.a16=null;
        self.a17=null;self.a18=null;self.a19=null;self.a20=null;
    }
}