contract VariousStrings {
    s1: String = "one";
    s2: String = "two";
    s3: String = "three";
    s4: String = "four";
    s5: String = "five";
    s6: String = "six";
    s7: String = "seven";
    s8: String = "eight";
    s9: String = "nine";
    s10: String = "ten";
    s11: String = "eleven";
    s12: String = "twelve";
    s13: String = "thirteen";
    s14: String = "fourteen";
    s15: String = "fifteen";
}