contract LargeBool {
    b1:Bool; b2:Bool; b3:Bool; b4:Bool; b5:Bool;
    b6:Bool; b7:Bool; b8:Bool; b9:Bool; b10:Bool;
    b11:Bool; b12:Bool; b13:Bool; b14:Bool; b15:Bool;
    b16:Bool; b17:Bool; b18:Bool; b19:Bool; b20:Bool;

    init() {
        self.b1=true;self.b2=false;self.b3=true;self.b4=false;self.b5=true;
        self.b6=true;self.b7=false;self.b8=true;self.b9=false;self.b10=true;
        self.b11=true;self.b12=false;self.b13=true;self.b14=false;self.b15=true;
        self.b16=true;self.b17=false;self.b18=true;self.b19=false;self.b20=true;
    }
}