contract ManyFields {
    f1: Int;
    f2: Bool;
    f3: Int;
    f4: Bool;
    f5: Int;
    f6: Bool;
    f7: Int;
    f8: Bool;
    f9: Int;
    f10: Bool;
    f11: Int;
    f12: Bool;
    f13: Int;
    f14: Bool;
    f15: Int;
    f16: Bool;
    f17: Int;
    f18: Bool;
    f19: Int;
    f20: Bool;
    
    init() {
        self.f1 = 1; self.f2 = true;
        self.f3 = 2; self.f4 = false;
        self.f5 = 3; self.f6 = true;
        self.f7 = 4; self.f8 = false;
        self.f9 = 5; self.f10 = true;
        self.f11 = 6; self.f12 = false;
        self.f13 = 7; self.f14 = true;
        self.f15 = 8; self.f16 = false;
        self.f17 = 9; self.f18 = true;
        self.f19 = 10; self.f20 = false;
    }
}