contract LongFieldsTest {
    a: Int = 0;
    b: Int = 0;
    c: Int = 0;
    d: Int = 0;
    e: Int = 0;
    f: Int = 0;
    g: Int = 0;
    h: Int = 0;
    i: Int = 0;
    j: Int = 0;
    k: Int = 0;
    l: Int = 0;
    m: Int = 0;
    n: Int = 0;
    o: Int = 0;
    p: Int = 0;
    q: Int = 0;
    r: Int = 0;
    s: Int = 0;
    t: Int = 0;
    u: Int = 0;
    v: Int = 0;
    w: Int = 0;
    x: Int = 0;
    y: Int = 0;
    z: Int = 0;

    init() {
        self.a = 1;
    }
}