contract ManyFields {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Bool = true;
    j: Bool = false;
    k: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");
    l: String = "x";
    m: String = "y";
    n: String = "z";
    o: Int = 9;
    p: Int = 10;
    q: Int = 11;
    r: Bool = true;
    s: String = "w";
    t: Int = 12;
}