contract ManyFields {
    i0: Int;
    i1: Int;
    i2: Int;
    i3: Int;
    i4: Int;
    i5: Int;
    i6: Int;
    i7: Int;
    i8: Int;
    i9: Int;
    b0: Bool;
    b1: Bool;
    b2: Bool;
    b3: Bool;
    b4: Bool;
    b5: Bool;
    b6: Bool;
    b7: Bool;
    b8: Bool;
    b9: Bool;
    s0: String;
    s1: String;
    s2: String;
    s3: String;
    s4: String;

    init() {
        self.i0 = 0; self.i1 = 0; self.i2 = 0; self.i3 = 0; self.i4 = 0;
        self.i5 = 0; self.i6 = 0; self.i7 = 0; self.i8 = 0; self.i9 = 0;
        self.b0 = false; self.b1 = false; self.b2 = false; self.b3 = false; self.b4 = false;
        self.b5 = false; self.b6 = false; self.b7 = false; self.b8 = false; self.b9 = false;
        self.s0 = ""; self.s1 = ""; self.s2 = ""; self.s3 = ""; self.s4 = "";
    }
}