contract ManyFields {
    x1: Int;
    x2: Int;
    x3: Int;
    x4: Int;
    x5: Int;
    x6: Int;
    x7: Int;
    x8: Int;
    x9: Int;
    x10: Int;
    x11: Int;
    x12: Int;
    x13: Int;
    x14: Int;
    x15: Int;
    x16: Int;
    x17: Int;
    x18: Int;
    x19: Int;
    x20: Int;

    init() {
        self.x1=1;self.x2=2;self.x3=3;self.x4=4;self.x5=5;
        self.x6=6;self.x7=7;self.x8=8;self.x9=9;self.x10=10;
        self.x11=11;self.x12=12;self.x13=13;self.x14=14;self.x15=15;
        self.x16=16;self.x17=17;self.x18=18;self.x19=19;self.x20=20;
    }
}