contract TestContract {
    a: Int; b: Int; c: Int; d: Int; e: Int;
    f: Int; g: Int; h: Int; i: Int; j: Int;
    k: Int; l: Int; m: Int; n: Int; o: Int;
    pa: Bool; pb: Bool; pc: Bool; pd: Bool; pe: Bool;
    s1: String; s2: String; s3: String; s4: String; s5: String;

    init() {
        self.a=1; self.b=2; self.c=3; self.d=4; self.e=5;
        self.f=6; self.g=7; self.h=8; self.i=9; self.j=10;
        self.k=11; self.l=12; self.m=13; self.n=14; self.o=15;
        self.pa=true; self.pb=false; self.pc=true; self.pd=false; self.pe=true;
        self.s1="a"; self.s2="b"; self.s3="c"; self.s4="d"; self.s5="e";
    }
}