contract HugeMix {
  a: Int?; b: Bool?; c: String?; d: Int; e: Bool; f: String; g: Int?; h: Int;
  i: Bool?; j: String; k: Int; l: Bool; m: String?; n: Int?; o: Bool?; p: String?;

  init() {
    self.a = null; self.b = true; self.c = null; self.d = 1; self.e = false; self.f = "f";
    self.g = 7; self.h = 8; self.i = null; self.j = "j"; self.k = 11; self.l = true;
    self.m = null; self.n = -5; self.o = false; self.p = null;
  }
}