contract LotsOfFields {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Bool = false;
    g: Bool = true;
    h: Bool = false;
    i: Bool = true;
    j: Int = 10;
    k: Int = 11;
    l: Bool = false;
    m: Int = 12;
    n: Bool = true;
    o: Int = -1;
    p: Int = -2;
    q: Bool = false;
    r: Int = 0;
    s: Bool = true;
    t: Int = 100;

    init() {
        self.o = 0;
        self.p = 0;
    }
}