struct A {
  a: Int;
}
struct B {
  b: Int;
}
struct C {
  c: Int;
}
struct D {
  d: Int;
}
struct E {
  e: Int;
}
struct F {
  f: Int;
}
struct G {
  g: Int;
}
struct H {
  h: Int;
}
struct I {
  i: Int;
}
struct J {
  j: Int;
}

contract ManyStructs {
    a: A = A{a:1};
    b: B = B{b:2};
    c: C = C{c:3};
    d: D = D{d:4};
    e: E = E{e:5};
    f: F = F{f:6};
    g: G = G{g:7};
    h: H = H{h:8};
    i: I = I{i:9};
    j: J = J{j:10};
}