contract LargeOptionalCombo {
    opt1: Int?;
    opt2: Bool?;
    opt3: String?;
    opt4: Address?;
    opt5: Cell?;
    opt6: Int?;
    opt7: Bool?;
    opt8: String?;
    opt9: Address?;
    opt10: Cell?;

    init() {
        self.opt1=null; self.opt2=null; self.opt3=null; self.opt4=null; self.opt5=null;
        self.opt6=null; self.opt7=null; self.opt8=null; self.opt9=null; self.opt10=null;
    }
}