contract LongFields {
    a: Int;
    b: Bool;
    c: Int;
    d: Bool;
    e: String;
    f: Int;
    g: Bool;
    h: String;
    i: Int;
    j: Bool;
    k: String;
    l: Int;
    m: Bool;
    n: String;
    o: Int;
    p: Bool;
    q: String;

    init() {
        self.a = 1;
        self.b = true;
        self.c = 2;
        self.d = false;
        self.e = "e";
        self.f = 3;
        self.g = true;
        self.h = "h";
        self.i = 4;
        self.j = false;
        self.k = "k";
        self.l = 5;
        self.m = true;
        self.n = "n";
        self.o = 6;
        self.p = false;
        self.q = "q";
    }
}