contract LargePrimitives {
    n1: Int;
    n2: Int;
    n3: Int;
    n4: Int;
    n5: Int;
    n6: Int;
    n7: Int;
    n8: Int;
    n9: Int;
    n10: Int;
    n11: Int;
    n12: Int;
    n13: Int;
    n14: Int;
    n15: Int;
    n16: Int;
    init() {
        self.n1=1; self.n2=2; self.n3=3; self.n4=4;
        self.n5=5; self.n6=6; self.n7=7; self.n8=8;
        self.n9=9; self.n10=10; self.n11=11; self.n12=12;
        self.n13=13; self.n14=14; self.n15=15; self.n16=16;
    }
}