contract TestContract {
    num1: Int = 1;
    num2: Int = 2;
    num3: Int = 3;
    bl1: Bool = true;
    bl2: Bool = false;
    bl3: Bool = true;
    txt1: String = "a";
    txt2: String = "b";
    txt3: String = "c";

    init() {
        self.num1 = 10;
        self.num2 = 20;
        self.num3 = 30;
        self.bl1 = false;
        self.bl2 = true;
        self.bl3 = false;
        self.txt1 = "x";
        self.txt2 = "y";
        self.txt3 = "z";
    }
}
