contract TestContract {
    x1: Int; x2: Int; x3: Int; x4: Int; x5: Int;
    b1: Bool; b2: Bool; b3: Bool; b4: Bool; b5: Bool;
    s1: String; s2: String; s3: String; s4: String; s5: String;
    x6: Int; x7: Int; x8: Int; x9: Int; x10: Int;
    b6: Bool; b7: Bool; b8: Bool; b9: Bool; b10: Bool;
    s6: String; s7: String; s8: String; s9: String; s10: String;
    x11: Int; x12: Int; x13: Int; x14: Int; x15: Int;
    b11: Bool; b12: Bool; b13: Bool; b14: Bool; b15: Bool;
    s11: String; s12: String; s13: String; s14: String; s15: String;

    init() {
        self.x1=1; self.x2=2; self.x3=3; self.x4=4; self.x5=5;
        self.b1=true; self.b2=false; self.b3=true; self.b4=false; self.b5=true;
        self.s1="a"; self.s2="b"; self.s3="c"; self.s4="d"; self.s5="e";
        self.x6=6; self.x7=7; self.x8=8; self.x9=9; self.x10=10;
        self.b6=true; self.b7=true; self.b8=false; self.b9=true; self.b10=false;
        self.s6="f"; self.s7="g"; self.s8="h"; self.s9="i"; self.s10="j";
        self.x11=11; self.x12=12; self.x13=13; self.x14=14; self.x15=15;
        self.b11=true; self.b12=false; self.b13=true; self.b14=false; self.b15=true;
        self.s11="k"; self.s12="l"; self.s13="m"; self.s14="n"; self.s15="o";
    }
}
