trait LargeTrait {
    t0: Int;
    t1: Int;
    t2: Int;
    t3: Int;
    t4: Int;
    t5: Int;
    t6: Int;
    t7: Int;
    t8: Int;
    t9: Int;
}

contract Test23 with LargeTrait {
    t0: Int;
    t1: Int;
    t2: Int;
    t3: Int;
    t4: Int;
    t5: Int;
    t6: Int;
    t7: Int;
    t8: Int;
    t9: Int;

    init() {
        self.t0=0; self.t1=1; self.t2=2; self.t3=3; self.t4=4;
        self.t5=5; self.t6=6; self.t7=7; self.t8=8; self.t9=9;
    }
}