struct BigOpt {
  f1: Int? = null;
  f2: Int? = null;
  f3: Int? = null;
  f4: Int? = null;
  f5: Int? = null;
  f6: Int? = null;
  f7: Int? = null;
  f8: Int? = null;
  f9: Int? = null;
  f10: Int? = null;
  f11: Int? = null;
  f12: Int? = null;
  f13: Int? = null;
  f14: Int? = null;
  f15: Int? = null;
  f16: Int? = null;
  f17: Int? = null;
  f18: Int? = null;
  f19: Int? = null;
  f20: Int? = null;
}

contract TestContract {
  big: BigOpt = BigOpt{};
}