contract Test(
    a: Int as int16,
    b: Int as int16,
    c: Int as int16,
    d: Int as int16,
    e: Int as int16,
    f: Int as int16,
    g: Int as int16,
    h: Int as int16,
    i: Int as int16,
    j: Int as int16,
    k: Int as int16,
    l: Int as int16,
    m: Int as int16,
    n: Int as int16,
    o: Int as int16,
    p: Int as int16,
    q: Int as int16,
    r: Int as int16,
    s: Int as int16,
    t: Int as int16,
) {
    receive() {}
}