contract LongContract {
    x0: Int;
    x1: Bool;
    x2: String;
    x3: Int?;
    x4: Bool?;
    x5: String?;
    x6: Int;
    x7: Bool;
    x8: String;
    x9: Int?;
    x10: Bool?;
    x11: String?;

    init() {
        self.x0=0; self.x1=true; self.x2="";
        self.x3=null; self.x4=null; self.x5=null;
        self.x6=6; self.x7=false; self.x8="foo";
        self.x9=null; self.x10=null; self.x11=null;
    }
}
