contract SizeStress {
    a:Int; b:Int; c:Int; d:Int; e:Int;
    f:Int; g:Int; h:Int; i:Int; j:Int;
    k:Int; l:Int; m:Int; n:Int; o:Int;
    p:Bool; q:Bool; r:Bool; s:Bool; t:Bool;
    u:String; v:String; w:String; x:String; y:String;

    init() {
        self.a=1; self.b=2; self.c=3; self.d=4; self.e=5;
        self.f=6; self.g=7; self.h=8; self.i=9; self.j=10;
        self.k=11; self.l=12; self.m=13; self.n=14; self.o=15;
        self.p=true; self.q=false; self.r=true; self.s=false; self.t=true;
        self.u="u"; self.v="v"; self.w="w"; self.x="x"; self.y="y";
    }
}