contract LargeFlat {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool?;
    e: String;
    f: String?;
    g: Int;
    h: Bool;
    i: Int?;
    j: Bool?;

    init() {
        self.a = 1;
        self.b = true;
        self.c = null;
        self.d = null;
        self.e = "x";
        self.f = null;
        self.g = 2;
        self.h = false;
        self.i = null;
        self.j = null;
    }
}