contract LargeOptionalCluster {
    a: Int?;
    b: Int?;
    c: Bool?;
    d: Bool?;
    e: String?;
    f: String?;
    g: Int?;
    h: Bool?;
    i: String?;
    j: Int?;
    k: Bool?;
    l: String?;

    init() {
        self.a = null;
        self.b = 1;
        self.c = null;
        self.d = true;
        self.e = null;
        self.f = "abc";
        self.g = null;
        self.h = false;
        self.i = null;
        self.j = 2;
        self.k = null;
        self.l = "xyz";
    }
}