contract LargeFields {
    a0: Int = 0;
    a1: Int = 1;
    a2: Int = 2;
    a3: Int = 3;
    a4: Int = 4;
    a5: Int = 5;
    a6: Int = 6;
    a7: Int = 7;
    a8: Int = 8;
    a9: Int = 9;
    a10: Int = 10;
    a11: Int = 11;
    a12: Int = 12;
    a13: Int = 13;
    a14: Int = 14;
    a15: Int = 15;

    init() {
        self.a0 = 0;
        self.a1 = 1;
        self.a2 = 2;
        self.a3 = 3;
        self.a4 = 4;
        self.a5 = 5;
        self.a6 = 6;
        self.a7 = 7;
        self.a8 = 8;
        self.a9 = 9;
        self.a10 = 10;
        self.a11 = 11;
        self.a12 = 12;
        self.a13 = 13;
        self.a14 = 14;
        self.a15 = 15;
    }
}