contract WideFields {
    a: Int = 1;
    b: Bool = true;
    c: String = "s";
    d: Int = 2;
    e: Bool = false;
    f: String = "t";
    g: Int = 3;
    h: Bool = true;
    i: String = "r";
    j: Int = 4;
    k: Bool = false;
    l: String = "u";
    m: Int = 5;
    n: Bool = true;
    o: String = "c";
    p: Int = 6;
    q: Bool = false;
    r: String = "t";
    s: Int = 7;
    t: Bool = true;
    u: String = "s";
}