contract LargeOptionalGroups {
    opt1: Int?;
    opt2: Int?;
    opt3: Int?;
    opt4: Bool?;
    opt5: Bool?;
    opt6: String?;
    opt7: String?;
    opt8: Address?;
    opt9: Cell?;
    opt10: Slice?;

    init() {
        self.opt1 = null;
        self.opt2 = null;
        self.opt3 = null;
        self.opt4 = null;
        self.opt5 = null;
        self.opt6 = null;
        self.opt7 = null;
        self.opt8 = null;
        self.opt9 = null;
        self.opt10 = null;
    }
}