contract WideTest {
    a0: Int = 0;
    a1: Bool = false;
    a2: String = "x";
    a3: Int = 3;
    a4: Bool = true;
    a5: String = "y";
    a6: Int = 6;
    a7: Bool = false;
    a8: String = "z";
    a9: Int = 9;
    a10: Bool = true;
    a11: String = "w";
    a12: Int = 12;
    a13: Bool = false;
    a14: String = "k";
    a15: Int = 15;
    a16: Bool = true;
    a17: String = "m";
    a18: Int = 18;
    a19: Bool = false;
    receive() {}
}