contract HugeContract {
    a: Int = 1;
    b: Int = 2;
    c: Int? = null;
    d: Int? = 4;
    e: Bool = true;
    f: Bool? = null;
    g: Bool? = false;
    h: String = "h";
    i: String? = "i";
    j: String? = null;
    k: Int = 11;
    l: Int? = null;
    m: Int? = 14;
    n: Bool = false;
    o: Bool? = null;
    p: Bool? = true;
    q: String = "q";
    r: String? = "r";
    s: String? = null;
    t: Int = 21;
    u: Int? = 22;
    v: Bool = true;
    w: Bool? = false;
    x: String = "x";
    y: String? = "y";
    z: String? = null;
    aa: Int = 101;
    ab: Int? = null;
    ac: Bool = false;
    ad: Bool? = null;
    ae: Bool? = true;
    af: String = "af";
    ag: String? = "ag";
    ah: String? = null;
    ai: Int = 777;
    aj: Int? = 888;
    ak: Bool = true;
    al: Bool? = false;
    am: String = "am";
    an: String? = "an";
    ao: String? = null;

    init() {
        self.a=10; self.b=20; self.c=30; self.d=40; self.e=false; self.f=true; self.g=false;
        self.h="hh"; self.i="ii"; self.j="jj"; self.k=110; self.l=120; self.m=130;
        self.n=true; self.o=false; self.p=true; self.q="qq"; self.r="rr"; self.s="ss";
        self.t=210; self.u=220; self.v=false; self.w=true; self.x="xx"; self.y="yy";
        self.z="zz"; self.aa=202; self.ab=303; self.ac=true; self.ad=false; self.ae=true;
        self.af="aff"; self.ag="agg"; self.ah="ahh"; self.ai=888; self.aj=999;
        self.ak=false; self.al=true; self.am="amm"; self.an="ann"; self.ao="aao";
    }
}