contract TestContract {
    a: Int = 0;
    b: Int = 1;
    c: Int = 2;
    d: Int = 3;
    e: Int = 4;
    f: Int = 5;
    g: Int = 6;
    h: Int = 7;
    i: Int = 8;
    j: Int = 9;
    k: Int = 10;
    l: Int = 11;
    m: Int = 12;
    n: Int = 13;
    o: Int = 14;
    p: Int = 15;
    q: Int = 16;
    r: Int = 17;
    s: Int = 18;
    t: Int = 19;

    init(){
        self.a=100;
        self.b=101;
        self.c=102;
        self.d=103;
        self.e=104;
        self.f=105;
        self.g=106;
        self.h=107;
        self.i=108;
        self.j=109;
        self.k=110;
        self.l=111;
        self.m=112;
        self.n=113;
        self.o=114;
        self.p=115;
        self.q=116;
        self.r=117;
        self.s=118;
        self.t=119;
    }
    receive(){}
}