contract BigOptional {
    n1: Int?;
    n2: Int?;
    n3: Int?;
    n4: Int?;
    n5: Int?;
    n6: Int?;
    n7: Int?;
    n8: Int?;
    n9: Int?;
    n10: Int?;

    init() {
        self.n1 = null;
        self.n2 = null;
        self.n3 = null;
        self.n4 = null;
        self.n5 = null;
        self.n6 = null;
        self.n7 = null;
        self.n8 = null;
        self.n9 = null;
        self.n10 = null;
    }
}