contract ManyFields {
    a: Int;
    b: Int?;
    c: Bool;
    d: Bool?;
    e: String;
    f: String?;
    g: Int;
    h: Bool;
    i: String;
    j: Int?;
    k: Bool?;
    l: String?;
    m: Int;
    n: Bool;
    o: String;

    init() {
        self.a = 1;
        self.b = null;
        self.c = true;
        self.d = null;
        self.e = "e";
        self.f = null;
        self.g = 7;
        self.h = false;
        self.i = "i";
        self.j = null;
        self.k = null;
        self.l = null;
        self.m = 13;
        self.n = true;
        self.o = "o";
    }
}