contract TestContract {
    f1: String = "";
    f2: String = "";
    f3: String = "";
    f4: String = "";
    f5: String = "";
    f6: String = "";
    f7: String = "";
    f8: String = "";
    f9: String = "";
    f10: String = "";
    f11: String = "";
    f12: String = "";
    f13: String = "";
    f14: String = "";
    f15: String = "";

    init() {
        self.f1 = "1";
        self.f2 = "2";
        self.f3 = "3";
        self.f4 = "4";
        self.f5 = "5";
        self.f6 = "6";
        self.f7 = "7";
        self.f8 = "8";
        self.f9 = "9";
        self.f10 = "10";
        self.f11 = "11";
        self.f12 = "12";
        self.f13 = "13";
        self.f14 = "14";
        self.f15 = "15";
    }
}
