contract LargeFields {
    a: Int;
    b: Int;
    c: Int;
    d: String;
    e: String;
    f: String;
    g: Bool;
    h: Bool;
    i: Bool;
    j: Int;
    k: String;
    l: Bool;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = "d";
        self.e = "e";
        self.f = "f";
        self.g = true;
        self.h = false;
        self.i = true;
        self.j = 4;
        self.k = "k";
        self.l = false;
    }
}