struct StringsPack {
    a: String;
    b: String;
    c: String;
    d: String;
    e: String;
    f: String;
    g: String;
    h: String;
}

contract ManyStrings {
    textData: StringsPack;

    init() {
        self.textData = StringsPack{
            a: "a",
            b: "b",
            c: "c",
            d: "d",
            e: "e",
            f: "f",
            g: "g",
            h: "h",
        };
    }
}