contract Test {
    f1: Int = 0;
    f2: Int = 1;
    f3: Int = 2;
    f4: Int = 3;
    f5: Int = 4;
    f6: Int = 5;
    f7: Int = 6;
    f8: Int = 7;
    f9: Int = 8;
    f10: Int = 9;
    f11: Int = 10;
    f12: Int = 11;
    f13: Int = 12;
    f14: Int = 13;
    f15: Int = 14;
    f16: Int = 15;
    f17: Int = 16;
    f18: Int = 17;
    f19: Int = 18;
    f20: Int = 19;

    init() {
        self.f1 = 0;
    }
}