contract ManyBool {
    b1: Bool = false;
    b2: Bool = false;
    b3: Bool = false;
    b4: Bool = false;
    b5: Bool = false;
    b6: Bool = false;
    b7: Bool = false;
    b8: Bool = false;
    b9: Bool = false;
    b10: Bool = false;

    init() {
        self.b1 = false;
        self.b2 = false;
        self.b3 = false;
        self.b4 = false;
        self.b5 = false;
        self.b6 = false;
        self.b7 = false;
        self.b8 = false;
        self.b9 = false;
        self.b10 = false;
    }
}