contract ManyFields {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Bool = true;
    g: Bool = false;
    h: Int = 10;
    i: Int = 11;
    j: Bool = true;
    k: Int = 12;
    l: Bool = false;
    m: Int = 13;
    n: Int = 14;
    o: Int = 15;
    p: Bool = true;
    q: Int = 16;
    r: Bool = false;
    s: Int = 17;
    t: Bool = true;

    receive() { }
}