contract ManyOptionals {
    o1: Int?;
    o2: Bool?;
    o3: String?;
    o4: Int?;
    o5: Bool?;
    o6: String?;
    o7: Int?;
    o8: Bool?;
    o9: String?;
    o10: Int?;

    init() {
        self.o1 = null;
        self.o2 = null;
        self.o3 = null;
        self.o4 = 4;
        self.o5 = true;
        self.o6 = "opt";
        self.o7 = null;
        self.o8 = false;
        self.o9 = "more";
        self.o10 = 10;
    }
}