contract ManyFields {
    a: Int = 1;
    b: Bool = false;
    c: String = "a";
    d: Int = 2;
    e: Bool = true;
    f: String = "b";
    g: Int = 3;
    h: Bool = false;
    i: String = "c";
    j: Int = 4;
    k: Bool = true;
    l: String = "d";
    m: Int = 5;
    n: Bool = false;
    o: String = "e";
    p: Int = 6;
    q: Bool = true;
    r: String = "f";
    s: Int = 7;
    t: Bool = false;
    u: String = "g";

    receive() {}
}