contract BigDefaultedOptionals {
    a: Int = 1;
    b: Bool = false;
    c: Address? = null;
    d: String = "";
    e: Bool = true;
    f: Int = 10;
    g: String = "g";
    h: Address? = null;
    i: Bool = false;
    j: Int = -1;
    k: Int = 123;
    l: Int = 456;
    m: Int = 789;
    n: Int = 101112;
    o: Int = 131415;
    p: Int = 161718;
    q: Int = 192021;
    r: Int = 222324;
    s: Int = 252627;
    t: Int = 282930;
}
