contract ManyFields {
    a: Int = 1;
    b: Bool = false;
    c: String = "x";
    d: Int = 2;
    e: Bool = true;
    f: String = "y";
    g: Int = 3;
    h: Bool = false;
    i: String = "z";
    j: Int = 4;
    k: Bool = true;
    l: String = "k";
    m: Int = 5;
    n: Bool = false;
    o: String = "m";
    p: Int = 6;
    q: Bool = true;
    r: String = "n";
    s: Int = 7;
    t: Bool = false;
    u: String = "o";
    v: Int = 8;
    w: Bool = true;
    x: String = "p";
    y: Int = 9;
    z: Bool = false;
    aa: String = "q";
    bb: Int = 10;
    cc: Bool = true;
    dd: String = "r";

    init() {
        self.a = 100;
    }
}