contract ManyFields {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;
    k: Int = 11;
    l: Int = 12;
    m: Int = 13;
    n: Int = 14;
    o: Int = 15;
    p: Int = 16;
    q: Int = 17;
    r: Int = 18;
    s: Int = 19;
    t: Int = 20;

    init() {
        self.a = 21;
        self.b = 22;
        self.c = 23;
        self.d = 24;
        self.e = 25;
        self.f = 26;
        self.g = 27;
        self.h = 28;
        self.i =29;
        self.j=30;
        self.k=31;
        self.l=32;
        self.m=33;
        self.n=34;
        self.o=35;
        self.p=36;
        self.q=37;
        self.r=38;
        self.s=39;
        self.t=40;
    }
}