contract ManyOptionals {
    o1: Int? = null;
    o2: Int? = null;
    o3: Int? = null;
    o4: Int? = null;
    o5: Int? = null;
    o6: Int? = null;
    o7: Int? = null;
    o8: Int? = null;
    o9: Int? = null;
    o10: Int? = null;

    init() {
        self.o1 = null;
        self.o2 = null;
        self.o3 = null;
        self.o4 = null;
        self.o5 = null;
        self.o6 = null;
        self.o7 = null;
        self.o8 = null;
        self.o9 = null;
        self.o10 = null;
    }
}