contract LongFields {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int?;
    f5: String;
    f6: Bool;
    f7: Int;
    f8: String;
    f9: Bool?;
    f10: String;
    
    init() {
        self.f1 = 1;
        self.f2 = false;
        self.f3 = "a";
        self.f4 = null;
        self.f5 = "b";
        self.f6 = true;
        self.f7 = 7;
        self.f8 = "c";
        self.f9 = true;
        self.f10 = "d";
    }
}