contract TestManyBools {
    b01: Bool = false; b02: Bool = false; b03: Bool = false; b04: Bool = false;
    b05: Bool = false; b06: Bool = false; b07: Bool = false; b08: Bool = false;
    b09: Bool = false; b10: Bool = false; b11: Bool = false; b12: Bool = false;
    b13: Bool = false; b14: Bool = false; b15: Bool = false; b16: Bool = false;
    b17: Bool = false; b18: Bool = false; b19: Bool = false; b20: Bool = false;
    b21: Bool = false; b22: Bool = false; b23: Bool = false; b24: Bool = false;
    b25: Bool = false; b26: Bool = false; b27: Bool = false; b28: Bool = false;
    b29: Bool = false; b30: Bool = false; b31: Bool = false; b32: Bool = false;
    b33: Bool = false; b34: Bool = false; b35: Bool = false; b36: Bool = false;
    b37: Bool = false; b38: Bool = false; b39: Bool = false; b40: Bool = false;
    b41: Bool = false; b42: Bool = false; b43: Bool = false; b44: Bool = false;
    b45: Bool = false; b46: Bool = false; b47: Bool = false; b48: Bool = false;
    b49: Bool = false; b50: Bool = false; b51: Bool = false; b52: Bool = false;
    b53: Bool = false; b54: Bool = false; b55: Bool = false; b56: Bool = false;
    b57: Bool = false; b58: Bool = false; b59: Bool = false; b60: Bool = false;
    b61: Bool = false; b62: Bool = false; b63: Bool = false; b64: Bool = false;
}