contract LotsOfFields {
    a0: Int = 0;
    a1: Int = 1;
    a2: Int = 2;
    a3: Int = 3;
    a4: Int = 4;
    a5: Int = 5;
    a6: Int = 6;
    a7: Int = 7;
    a8: Int = 8;
    a9: Int = 9;
    b0: Bool = true;
    b1: Bool = false;
    b2: Bool = true;
    b3: Bool = false;
    s0: String = "zero";
    s1: String = "one";
    s2: String = "two";
    s3: String = "three";
    s4: String = "four";
    s5: String = "five";
}