contract ManyFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool;
    e: Int;
    f: Int?;
    g: Bool;
    h: Int;
    i: Bool?;
    j: Int;
    k: Bool;
    l: Int?;
    m: Bool;

    init() {
        self.a = 1;
        self.b = true;
        self.c = null;
        self.d = false;
        self.e = 5;
        self.f = null;
        self.g = true;
        self.h = 10;
        self.i = null;
        self.j = 20;
        self.k = false;
        self.l = null;
        self.m = true;
    }
}