contract LongContract {
    aa: Int;
    bb: Bool;
    cc: String;
    dd: Int?;
    ee: Bool?;
    ff: String?;
    gg: Int;
    hh: Bool;
    ii: String;
    jj: Int?;
    kk: Bool?;
    ll: String?;
    mm: Int;
    nn: Bool;
    oo: String;
    pp: Int?;
    qq: Bool?;
    rr: String?;
    ss: Int;
    tt: Bool;
    uu: String;
    vv: Int?;
    ww: Bool?;
    xx: String?;

    init() {
        self.aa=0; self.bb=false; self.cc=""; self.dd=null; self.ee=null; self.ff=null;
        self.gg=0; self.hh=false; self.ii=""; self.jj=null; self.kk=null; self.ll=null;
        self.mm=0; self.nn=false; self.oo=""; self.pp=null; self.qq=null; self.rr=null;
        self.ss=0; self.tt=false; self.uu=""; self.vv=null; self.ww=null; self.xx=null;
    }
}