contract LongList {
    a1: Int = 1;
    a2: Int = 2;
    a3: Int = 3;
    a4: Int = 4;
    a5: Int = 5;
    a6: Int = 6;
    a7: Int = 7;
    a8: Int = 8;
    a9: Int = 9;
    a10: Int = 10;
    a11: Int = 11;
    a12: Int = 12;
    a13: Int = 13;
    a14: Int = 14;
    a15: Int = 15;
    a16: Int = 16;

    init() {
        self.a1 = 11;
        self.a2 = 12;
        self.a3 = 13;
        self.a4 = 14;
        self.a5 = 15;
        self.a6 = 16;
        self.a7 = 17;
        self.a8 = 18;
        self.a9 = 19;
        self.a10 = 20;
        self.a11 = 21;
        self.a12 = 22;
        self.a13 = 23;
        self.a14 = 24;
        self.a15 = 25;
        self.a16 = 26;
    }
}
