contract LargeContract {
    f1: Int;
    f2: Int;
    f3: Bool;
    f4: Bool;
    f5: String;
    f6: String;
    f7: Int?;
    f8: Bool?;
    f9: String?;
    f10: Int;
    f11: Int;
    f12: Bool;
    f13: Bool;
    f14: String;
    f15: String;
    init() {
        self.f1 = 1;
        self.f2 = 2;
        self.f3 = true;
        self.f4 = false;
        self.f5 = "a";
        self.f6 = "b";
        self.f7 = null;
        self.f8 = null;
        self.f9 = null;
        self.f10 = 10;
        self.f11 = 11;
        self.f12 = false;
        self.f13 = true;
        self.f14 = "c";
        self.f15 = "d";
    }
}