contract TestContract {
    f1: Bool = true;
    f2: Bool = false;
    f3: Bool = true;
    f4: Bool = false;
    f5: Bool = true;
    f6: Bool = false;
    f7: Bool = true;
    f8: Bool = false;
    f9: Bool = true;
    f10: Bool = false;
    f11: Bool = true;
    f12: Bool = false;
    f13: Bool = true;
    f14: Bool = false;
    f15: Bool = true;
    f16: Bool = false;
    f17: Bool = true;
    f18: Bool = false;
    f19: Bool = true;
    f20: Bool = false;
    f21: Bool = true;
    f22: Bool = false;
    f23: Bool = true;
    f24: Bool = false;
    f25: Bool = true;
}