// Testing very large list of persistent fields (50 Int fields)
contract GiantContract {
    i1: Int;  i2: Int;  i3: Int;  i4: Int;  i5: Int;
    i6: Int;  i7: Int;  i8: Int;  i9: Int;  i10: Int;
    i11: Int; i12: Int; i13: Int; i14: Int; i15: Int;
    i16: Int; i17: Int; i18: Int; i19: Int; i20: Int;
    i21: Int; i22: Int; i23: Int; i24: Int; i25: Int;
    i26: Int; i27: Int; i28: Int; i29: Int; i30: Int;
    i31: Int; i32: Int; i33: Int; i34: Int; i35: Int;
    i36: Int; i37: Int; i38: Int; i39: Int; i40: Int;
    i41: Int; i42: Int; i43: Int; i44: Int; i45: Int;
    i46: Int; i47: Int; i48: Int; i49: Int; i50: Int;

    init() {
        self.i1=1; self.i2=2; self.i3=3; self.i4=4; self.i5=5;
        self.i6=6; self.i7=7; self.i8=8; self.i9=9; self.i10=10;
        self.i11=11; self.i12=12; self.i13=13; self.i14=14; self.i15=15;
        self.i16=16; self.i17=17; self.i18=18; self.i19=19; self.i20=20;
        self.i21=21; self.i22=22; self.i23=23; self.i24=24; self.i25=25;
        self.i26=26; self.i27=27; self.i28=28; self.i29=29; self.i30=30;
        self.i31=31; self.i32=32; self.i33=33; self.i34=34; self.i35=35;
        self.i36=36; self.i37=37; self.i38=38; self.i39=39; self.i40=40;
        self.i41=41; self.i42=42; self.i43=43; self.i44=44; self.i45=45;
        self.i46=46; self.i47=47; self.i48=48; self.i49=49; self.i50=50;
    }
}