contract DeeplyNestedOptionalsContract {
    field1: Int?;
    field2: Int?;
    field3: Int?;
    field4: Int?;
    field5: Int?;
    field6: Int?;
    field7: Int?;
    field8: Int?;
    field9: Int?;
    field10: Int?;

    init() {
        self.field1 = null;
        self.field2 = null;
        self.field3 = null;
        self.field4 = null;
        self.field5 = null;
        self.field6 = null;
        self.field7 = null;
        self.field8 = null;
        self.field9 = null;
        self.field10 = null;
    }
}