contract ManyOptionalFields {
    a: Int? = null;
    b: Int? = null;
    c: Int? = null;
    d: Int? = null;
    e: Bool? = null;
    f: Bool? = null;
    g: Bool? = null;
    h: Bool? = null;
    i: String? = null;
    j: String? = null;
    k: String? = null;
    l: String? = null;
    m: Int? = 1;
    n: Int? = null;
    o: Int? = 0;
    p: Bool? = true;
    q: Bool? = null;
    r: String? = "hello";
    s: String? = null;
    t: Int? = null;
}
