contract LargeVarList {
    v1: Int;
    v2: Int;
    v3: Int;
    v4: Int;
    v5: Int;
    v6: Int;
    v7: Int;
    v8: Int;
    v9: Int;
    v10: Int;
    v11: Int;
    v12: Int;
    v13: Int;
    v14: Int;
    v15: Int;

    init() {
        self.v1 = 1;
        self.v2 = 2;
        self.v3 = 3;
        self.v4 = 4;
        self.v5 = 5;
        self.v6 = 6;
        self.v7 = 7;
        self.v8 = 8;
        self.v9 = 9;
        self.v10 = 10;
        self.v11 = 11;
        self.v12 = 12;
        self.v13 = 13;
        self.v14 = 14;
        self.v15 = 15;
    }
}