contract ManyVars {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;
    k: Bool = true;
    l: Bool = false;
    m: String = "a";
    n: String = "b";
    o: String = "c";
    p: String = "d";
    q: String? = null;
    r: Int? = null;
    s: Bool? = null;
    t: String? = null;

    init() {}
}