contract ManyBools {
    b0: Bool = true;
    b1: Bool = false;
    b2: Bool = true;
    b3: Bool = false;
    b4: Bool = true;
    b5: Bool = false;
    b6: Bool = true;
    b7: Bool = false;
    b8: Bool = true;
    b9: Bool = false;

    init() {
        self.b0 = false;
        self.b1 = true;
        self.b2 = false;
        self.b3 = true;
        self.b4 = false;
        self.b5 = true;
        self.b6 = false;
        self.b7 = true;
        self.b8 = false;
        self.b9 = true;
    }
}