contract Enough {
    p1: Int; p2: Int; p3: Int; p4: Int; p5: Int;
    p6: Int; p7: Int; p8: Int; p9: Int; p10: Int;
    p11: Int; p12: Int; p13: Int; p14: Int; p15: Int;
    p16: Int; p17: Int; p18: Int; p19: Int; p20: Int;

    init() {
        self.p1=1; self.p2=2; self.p3=3; self.p4=4; self.p5=5;
        self.p6=6; self.p7=7; self.p8=8; self.p9=9; self.p10=10;
        self.p11=11; self.p12=12; self.p13=13; self.p14=14; self.p15=15;
        self.p16=16; self.p17=17; self.p18=18; self.p19=19; self.p20=20;
    }
}
