// Large number of optional fields without nested structs
contract TestContract {
    a: Int?;
    b: Int?;
    c: Int?;
    d: Int?;
    e: Int?;
    f: Int?;
    g: Int?;
    h: Int?;
    i: Int?;
    j: Int?;
    k: Int?;
    l: Int?;
    m: Int?;
    n: Int?;
    o: Int?;
    p: Int?;
    q: Int?;
    r: Int?;
    s: Int?;
    t: Int?;
    u: Int?;
    v: Int?;
    w: Int?;
    x: Int?;
    y: Int?;
    z: Int?;

    init() {
        self.a = null;
        self.b = null;
        self.c = null;
        self.d = null;
        self.e = null;
        self.f = null;
        self.g = null;
        self.h = null;
        self.i = null;
        self.j = null;
        self.k = null;
        self.l = null;
        self.m = null;
        self.n = null;
        self.o = null;
        self.p = null;
        self.q = null;
        self.r = null;
        self.s = null;
        self.t = null;
        self.u = null;
        self.v = null;
        self.w = null;
        self.x = null;
        self.y = null;
        self.z = null;
    }
}