contract LongPrimitiveFields {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool?;
    f: String;
    g: Int;
    h: Bool?;
    i: String?;
    j: Int;
    k: String;
    l: Bool;
    m: Bool?;
    n: String;
    o: Int;

    init() {
        self.a = 1;
        self.b = false;
        self.c = "a";
        self.d = null;
        self.e = true;
        self.f = "b";
        self.g = 2;
        self.h = null;
        self.i = "c";
        self.j = 3;
        self.k = "d";
        self.l = true;
        self.m = null;
        self.n = "e";
        self.o = 4;
    }
}