contract LargeMixed {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool?;
    f: String?;
    g: Int;
    h: Bool;
    i: String;
    j: Int?;
    k: Bool?;
    l: String?;

    init() {
        self.a = 1;
        self.b = false;
        self.c = "a";
        self.d = null;
        self.e = true;
        self.f = null;
        self.g = 7;
        self.h = true;
        self.i = "i";
        self.j = null;
        self.k = false;
        self.l = null;
    }
}