contract ManyFields {
    i0: Int;
    i1: Int;
    i2: Int;
    i3: Int;
    i4: Int;
    i5: Int;
    i6: Int;
    i7: Int;
    i8: Int;
    i9: Int;
    s0: String;
    s1: String;
    s2: String;
    s3: String;
    s4: String;
    s5: String;
    s6: String;
    s7: String;
    s8: String;
    s9: String;

    init() {
        self.i0 = 0;
        self.i1 = 1;
        self.i2 = 2;
        self.i3 = 3;
        self.i4 = 4;
        self.i5 = 5;
        self.i6 = 6;
        self.i7 = 7;
        self.i8 = 8;
        self.i9 = 9;
        self.s0 = "s0";
        self.s1 = "s1";
        self.s2 = "s2";
        self.s3 = "s3";
        self.s4 = "s4";
        self.s5 = "s5";
        self.s6 = "s6";
        self.s7 = "s7";
        self.s8 = "s8";
        self.s9 = "s9";
    }
}