contract BigFields {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Int;
    f: Int;
    g: Bool;
    h: Bool;
    i: Bool;
    j: String;
    k: String;
    l: String;
    m: String;
    n: Bool?;
    o: Int?;
    p: String?;
    q: Bool?;
    r: Int?;
    s: Bool;
    t: Bool; 

    init() {
        self.a=1; self.b=2; self.c=3; self.d=4; self.e=5; self.f=6;
        self.g=true; self.h=false; self.i=true; self.j="a"; self.k="b";
        self.l="c"; self.m="d"; self.n=null; self.o=null; self.p=null;
        self.q=null; self.r=null; self.s=true; self.t=false;
    }
}