contract HUGE {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Bool;
    f: Int;
    g: Int;
    h: Bool;
    i: Int;
    j: Int;
    k: Int;
    l: Int;
    m: Bool;
    n: Int;
    o: Int;
    p: Bool;
    q: Int;
    r: Int;
    s: Int;
    t: Int;
    u: Bool;
    v: Bool;
    w: Bool;
    x: Bool;
    y: Bool;
    z: Bool;

    init() {
        self.a=1; self.b=2; self.c=3; self.d=4; self.e=true;
        self.f=5; self.g=6; self.h=false; self.i=7; self.j=8;
        self.k=9; self.l=10; self.m=true; self.n=11; self.o=12;
        self.p=false; self.q=13; self.r=14; self.s=15; self.t=16;
        self.u=true; self.v=false; self.w=true; self.x=false;
        self.y=true; self.z=false;
    }
}