contract Test19 {
  seq1: Int = 1;
  seq2: Int = 2;
  seq3: Int = 3;
  seq4: Int = 4;
  seq5: Int = 5;
  seq6: Int = 6;
  seq7: Int = 7;
  seq8: Int = 8;
  seq9: Int = 9;
  seq10: Int = 10;
  seq11: Int = 11;
  seq12: Int = 12;
  seq13: Int = 13;
  seq14: Int = 14;
  seq15: Int = 15;
  seq16: Int = 16;
  seq17: Int = 17;
  seq18: Int = 18;
  seq19: Int = 19;
  seq20: Int = 20;
  seq21: Int = 21;
  seq22: Int = 22;
  seq23: Int = 23;
  seq24: Int = 24;
  seq25: Int = 25;

  init() {}
}