contract ManyFields {
    a: Int;
    b: Bool;
    c: String;
    d: Int;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int;
    k: Bool;
    l: String;
    m: Int;
    n: Bool;
    o: String;
    p: Int;
    q: Bool;
    r: String;
    s: Int;
    t: Bool;
    u: String;

    init() {
        self.a = 1;
        self.b = true;
        self.c = "x";
        self.d = 2;
        self.e = false;
        self.f = "y";
        self.g = 3;
        self.h = true;
        self.i = "z";
        self.j = 4;
        self.k = false;
        self.l = "m";
        self.m = 5;
        self.n = true;
        self.o = "n";
        self.p = 6;
        self.q = false;
        self.r = "o";
        self.s = 7;
        self.t = true;
        self.u = "p";
    }
}