contract LargeOptionalGroups {
    a: Int?;
    b: Int?;
    c: Bool?;
    d: Bool?;
    e: Cell?;
    f: Cell?;
    g: Slice?;
    h: Slice?;
    i: String?;
    j: String?;
    k: Address?;
    l: Address?;

    init() {
        self.a=null; self.b=null; self.c=null; self.d=null; self.e=null; self.f=null;
        self.g=null; self.h=null; self.i=null; self.j=null; self.k=null; self.l=null;
    }
}