contract LargeOptionalFields {
    a: Int?;
    b: Int?;
    c: Bool?;
    d: Address?;
    e: Cell?;
    f: String?;
    g: Int?;
    h: Bool?;
    i: Address?;
    j: Cell?;
    k: String?;
    l: Bool?;
    m: Int?;
    n: Address?;
    o: String?;

    init() {
        self.a = null;
        self.b = null;
        self.c = null;
        self.d = null;
        self.e = null;
        self.f = null;
        self.g = null;
        self.h = null;
        self.i = null;
        self.j = null;
        self.k = null;
        self.l = null;
        self.m = null;
        self.n = null;
        self.o = null;
    }
}