contract ManyFields {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Bool = true;
    g: Bool = false;
    h: String = "hi";
    i: String = "bye";
    j: Int = 6;
    k: Int = 7;
    l: Int = 8;
    m: Int = 9;
    n: Int = 10;
    o: Bool = true;
    p: Bool = false;
    q: String = "foo";
    r: String = "bar";
    s: Int = 11;
    t: Int = 12;
    init() {}
}