contract BigFlat {
    f1: Int;
    f2: Int as uint8;
    f3: Int as int64;
    f4: Bool;
    f5: String;
    f6: Int?;
    f7: Bool?;
    f8: String;
    f9: String;
    f10: Int;
    f11: Int;
    f12: Int as uint64;
    f13: Bool;
    f14: Int;
    f15: String;
    f16: Bool;
    f17: Int;
    f18: String;
    f19: Int?;
    f20: String;

    init() {
        self.f1=1; self.f2=2; self.f3=3; self.f4=true; self.f5="5";
        self.f6=null; self.f7=false; self.f8="8"; self.f9="9"; self.f10=10;
        self.f11=11; self.f12=12; self.f13=true; self.f14=14; self.f15="15";
        self.f16=false; self.f17=17; self.f18="18"; self.f19=null; self.f20="20";
    }
}