contract LongFieldList {
    f1: Int;
    f2: Bool;
    f3: String; 
    f4: Int;
    f5: Bool;
    f6: String;
    f7: Int;
    f8: Bool;
    f9: String;
    f10: Int;
    f11: Bool;
    f12: String;
    f13: Int;
    f14: Bool;
    f15: String;

    init() {
        self.f1=1; self.f2=true; self.f3="a";
        self.f4=2; self.f5=false; self.f6="b";
        self.f7=3; self.f8=true; self.f9="c";
        self.f10=4; self.f11=false; self.f12="d";
        self.f13=5; self.f14=true; self.f15="e";
    }
}
