contract Test {
  a0: Int;
  a1: Int;
  a2: Int;
  a3: Int;
  a4: Int;
  a5: Int;
  a6: Int;
  a7: Int;
  a8: Int;
  a9: Int;
  a10: Int;
  a11: Int;
  a12: Int;
  a13: Int;
  a14: Int;
  a15: Int;
  a16: Int;
  a17: Int;
  a18: Int;
  a19: Int;
  a20: Int;
  a21: Int;
  a22: Int;
  a23: Int;
  a24: Int;

  init() {
    self.a0=0; self.a1=1; self.a2=2; self.a3=3; self.a4=4;
    self.a5=5; self.a6=6; self.a7=7; self.a8=8; self.a9=9;
    self.a10=10; self.a11=11; self.a12=12; self.a13=13; self.a14=14;
    self.a15=15; self.a16=16; self.a17=17; self.a18=18; self.a19=19;
    self.a20=20; self.a21=21; self.a22=22; self.a23=23; self.a24=24;
  }
}