struct O {
    val: Int;
}

contract ArrayLike {
    e1: O;
    e2: O;
    e3: O;
    e4: O;
    e5: O;
    e6: O;
    e7: O;
    e8: O;
    e9: O;
    e10: O;

    init() {
        self.e1 = O{val:1};
        self.e2 = O{val:2};
        self.e3 = O{val:3};
        self.e4 = O{val:4};
        self.e5 = O{val:5};
        self.e6 = O{val:6};
        self.e7 = O{val:7};
        self.e8 = O{val:8};
        self.e9 = O{val:9};
        self.e10 = O{val:10};
    }
}