contract LongFields {
    a: Int;  b: Int;  c: Int;  d: Int;  e: Int;
    f: Bool; g: Bool; h: Bool; i: Bool; j: Bool;
    k: String; l: String; m: String; n: String; o: String;
    p: Int;  q: Int;  r: Int;  s: Int;  t: Int;
    u: Bool; v: Bool; w: Bool; x: Bool; y: Bool;
    z: String;

    init() {
        self.a = 1; self.b = 2; self.c = 3; self.d = 4; self.e = 5;
        self.f = true; self.g = false; self.h = true; self.i = false; self.j = true;
        self.k = "A"; self.l = "B"; self.m = "C"; self.n = "D"; self.o = "E";
        self.p = 6; self.q = 7; self.r = 8; self.s = 9; self.t = 10;
        self.u = false; self.v = true; self.w = false; self.x = true; self.y = false;
        self.z = "Z";
    }
}
