contract Test {
    str1: String?;
    str2: String?;
    str3: String?;
    str4: String?;
    str5: String?;
    str6: String?;
    str7: String?;
    str8: String?;
    str9: String?;
    str10: String?;

    init() {
        self.str1 = "a";
        self.str2 = "b";
        self.str3 = null;
        self.str4 = "d";
        self.str5 = null;
        self.str6 = "f";
        self.str7 = null;
        self.str8 = "h";
        self.str9 = null;
        self.str10 = "j";
    }
}