contract TestContract {
    first: Int = 1;
    second: Int = 2;
    third: Int = 3;
    fourth: Int = 4;
    fifth: Int = 5;
    sixth: Int = 6;
    seventh: Int = 7;
    eighth: Int = 8;
    ninth: Int = 9;
    tenth: Int = 10;
    eleventh: Int = 11;
    twelfth: Int = 12;
    thirteenth: Int = 13;
    fourteenth: Int = 14;
    fifteenth: Int = 15;
    sixteenth: Int = 16;
    seventeenth: Int = 17;
    eighteenth: Int = 18;
    nineteenth: Int = 19;
    twentieth: Int = 20;
}