// Large contract field list, wider not deeper
contract TestContract {
    a: Int;
    b: Int?;
    c: Bool;
    d: Bool?;
    e: String;
    f: String;
    g: String;
    h: Bool;
    i: Int;
    j: Bool?;
    k: Int?;
    l: String;
    m: Bool;

    init() {
        self.a = 1;
        self.b = null;
        self.c = true;
        self.d = false;
        self.e = "e";
        self.f = "f";
        self.g = "g";
        self.h = false;
        self.i = 9;
        self.j = null;
        self.k = 10;
        self.l = "L";
        self.m = true;
    }
}