contract TestContract {
    veryLongList1: Int;
    veryLongList2: Int;
    veryLongList3: Int;
    veryLongList4: Int;
    veryLongList5: Int;
    veryLongList6: Int;
    veryLongList7: Int;
    veryLongList8: Int;
    veryLongList9: Int;
    veryLongList10: Int;
    veryLongList11: Int;
    veryLongList12: Int;
    veryLongList13: Int;
    veryLongList14: Int;
    veryLongList15: Int;
    veryLongList16: Int;
    veryLongList17: Int;
    veryLongList18: Int;
    veryLongList19: Int;
    veryLongList20: Int;

    init() {
        self.veryLongList1=1;  self.veryLongList2=2;  self.veryLongList3=3; self.veryLongList4=4; self.veryLongList5=5;
        self.veryLongList6=6;  self.veryLongList7=7;  self.veryLongList8=8; self.veryLongList9=9; self.veryLongList10=10;
        self.veryLongList11=11;self.veryLongList12=12;self.veryLongList13=13;self.veryLongList14=14;self.veryLongList15=15;
        self.veryLongList16=16;self.veryLongList17=17;self.veryLongList18=18;self.veryLongList19=19;self.veryLongList20=20;
    }
}