contract LargeOptionals {
    f0: Int?;
    f1: Int?;
    f2: Int?;
    f3: Int?;
    f4: Int?;
    f5: Int?;
    f6: Int?;
    f7: Int?;
    f8: Int?;
    f9: Int?;
    f10: Int?;
    f11: Int?;
    f12: Int?;
    f13: Int?;
    f14: Int?;
    f15: Int?;
    f16: Int?;
    f17: Int?;
    f18: Int?;
    f19: Int?;
    f20: Int?;
    f21: Int?;
    f22: Int?;
    f23: Int?;
    f24: Int?;

    init() {
        self.f0 = null;
        self.f1 = null;
        self.f2 = null;
        self.f3 = null;
        self.f4 = null;
        self.f5 = null;
        self.f6 = null;
        self.f7 = null;
        self.f8 = null;
        self.f9 = null;
        self.f10 = null;
        self.f11 = null;
        self.f12 = null;
        self.f13 = null;
        self.f14 = null;
        self.f15 = null;
        self.f16 = null;
        self.f17 = null;
        self.f18 = null;
        self.f19 = null;
        self.f20 = null;
        self.f21 = null;
        self.f22 = null;
        self.f23 = null;
        self.f24 = null;
    }
}