contract ManyFields {
    a: Int;
    b: Int;
    c: Int;
    d: Bool;
    e: String;
    f: Bool;
    g: String;
    h: Int?;
    i: Bool;
    j: Int;
    k: String;
    l: Int?;
    m: Bool;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = true;
        self.e = "e";
        self.f = false;
        self.g = "g";
        self.h = null;
        self.i = true;
        self.j = 10;
        self.k = "k";
        self.l = null;
        self.m = false;
    }
}