contract ManyStrings {
    a: String = "a";
    b: String = "b";
    c: String = "c";
    d: String = "d";
    e: String = "e";
    f: String = "f";
    g: String = "g";
    h: String = "h";
    i: String = "i";
    j: String = "j";
    k: String = "k";
    l: String = "l";
    m: String = "m";
    n: String = "n";
    o: String = "o";
    p: String = "p";
    q: String = "q";
    r: String = "r";
    s: String = "s";
    t: String = "t";

    init() {
        self.a="A"; self.b="B"; self.c="C"; self.d="D"; self.e="E";
        self.f="F"; self.g="G"; self.h="H"; self.i="I"; self.j="J";
        self.k="K"; self.l="L"; self.m="M"; self.n="N"; self.o="O";
        self.p="P"; self.q="Q"; self.r="R"; self.s="S"; self.t="T";
    }
}
