contract LargeFieldList {
    a: Int;  b: Int;   c: Int;   d: Int;   e: Int;
    f: Bool; g: Bool; h: Bool;  i: Bool;  j: Bool;
    k: String; l: String; m: String; n: String; o: String;

    init() {
        self.a=0; self.b=1; self.c=2; self.d=3; self.e=4;
        self.f=true; self.g=false; self.h=true; self.i=false; self.j=true;
        self.k="A"; self.l="B"; self.m="C"; self.n="D"; self.o="E";
    }
}