// Testing high count of persistent optionals with default null and explicit init assignment
contract LotsOfOptionals {
    a: Int?;
    b: Int?;
    c: Int?;
    d: Int?;
    e: Int?;
    f: Int?;
    g: Int?;
    h: Int?;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = 4;
        self.e = 5;
        self.f = 6;
        self.g = 7;
        self.h = 8;
    }

    receive() {
        self.a = self.a;
    }
}