contract TestManyFields {
  a: Int;
  b: Bool;
  c: String;
  d: Int?;
  e: Bool;
  f: String;
  g: Int;
  h: Bool;
  i: String;
  j: Int?;
  k: Bool;
  l: String;
  m: Int;
  n: Bool;
  o: String;

  init() {
    self.a = 1;
    self.b = true;
    self.c = "c";
    self.d = null;
    self.e = false;
    self.f = "f";
    self.g = 2;
    self.h = true;
    self.i = "i";
    self.j = null;
    self.k = true;
    self.l = "l";
    self.m = 3;
    self.n = false;
    self.o = "o";
  }
}