contract LargeContract {
    f1: Int; f2: Bool; f3: String; f4: Int?; f5: Bool?; f6: String?;
    f7: Int; f8: Bool; f9: String; f10: Int?; f11: Bool?; f12: String?;
    f13: Int; f14: Bool; f15: String; f16: Int?; f17: Bool?; f18: String?;

    init() {
        self.f1 = 1; self.f2 = true; self.f3 = "a"; self.f4 = null; self.f5 = null; self.f6 = null;
        self.f7 = 7; self.f8 = false; self.f9 = "b"; self.f10 = null; self.f11 = true; self.f12 = null;
        self.f13 = 13; self.f14 = true; self.f15 = "c"; self.f16 = null; self.f17 = null; self.f18 = "zzz";
    }
}
