struct Tiny { a: Int }

contract TestContract {
    arr0: Tiny = Tiny{a:0};
    arr1: Tiny = Tiny{a:1};
    arr2: Tiny = Tiny{a:2};
    arr3: Tiny = Tiny{a:3};
    arr4: Tiny = Tiny{a:4};
    arr5: Tiny = Tiny{a:5};
    arr6: Tiny = Tiny{a:6};
    arr7: Tiny = Tiny{a:7};
    arr8: Tiny = Tiny{a:8};
    arr9: Tiny = Tiny{a:9};
    arr10: Tiny = Tiny{a:10};
    arr11: Tiny = Tiny{a:11};
    arr12: Tiny = Tiny{a:12};
    arr13: Tiny = Tiny{a:13};

    init() {
        self.arr0 = Tiny{a:100};
        self.arr1 = Tiny{a:101};
        self.arr2 = Tiny{a:102};
        self.arr3 = Tiny{a:103};
        self.arr4 = Tiny{a:104};
        self.arr5 = Tiny{a:105};
        self.arr6 = Tiny{a:106};
        self.arr7 = Tiny{a:107};
        self.arr8 = Tiny{a:108};
        self.arr9 = Tiny{a:109};
        self.arr10 = Tiny{a:110};
        self.arr11 = Tiny{a:111};
        self.arr12 = Tiny{a:112};
        self.arr13 = Tiny{a:113};
    }
}