contract ManyOptionals {
  a: Int?; b: Int?; c: Int?; d: Int?; e: Int?;
  f: Bool?; g: Bool?; h: Bool?; i: Bool?; j: Bool?;
  k: String?; l: String?; m: String?; n: String?; o: String?;
  p: Address?; q: Address?; r: Address?; s: Address?; t: Address?;

  init() {
    self.a=null; self.b=null; self.c=null; self.d=null; self.e=null;
    self.f=null; self.g=null; self.h=null; self.i=null; self.j=null;
    self.k=null; self.l=null; self.m=null; self.n=null; self.o=null;
    self.p=null; self.q=null; self.r=null; self.s=null; self.t=null;
  }
}