contract ManyOptionals {
    o1: Int?;
    o2: Int?;
    o3: Bool?;
    o4: Address?;
    o5: String?;
    o6: Slice?;
    o7: Int?;
    o8: Int?;
    o9: Bool?;
    o10: Address?;
    
    init() {
        self.o1 = null;
        self.o2 = null;
        self.o3 = null;
        self.o4 = null;
        self.o5 = null;
        self.o6 = null;
        self.o7 = null;
        self.o8 = null;
        self.o9 = null;
        self.o10 = null;
    }
}