contract ContractManyFields {
  var1: Int;
  var2: Int;
  var3: Int;
  var4: Int;
  var5: Int;
  var6: Int;
  var7: Int;
  var8: Int;
  var9: Int;
  var10: Int;
  var11: Int;
  var12: Int;
  var13: Int;
  var14: Int;
  var15: Int;
  var16: Int;
  var17: Int;
  var18: Int;
  var19: Int;
  var20: Int;
  var21: Int;

  init() {
    self.var1=1; self.var2=2; self.var3=3; self.var4=4; self.var5=5;
    self.var6=6; self.var7=7; self.var8=8; self.var9=9; self.var10=10;
    self.var11=11; self.var12=12; self.var13=13; self.var14=14; self.var15=15;
    self.var16=16; self.var17=17; self.var18=18; self.var19=19; self.var20=20;
    self.var21=21;
  }
}
