contract ManyPrimitives {
    a1: Int;
    a2: Bool;
    a3: String;
    a4: Int;
    a5: Bool;
    a6: String;
    a7: Int;
    a8: Bool;
    a9: String;
    a10: Int;
    a11: Bool;
    a12: String;
    a13: Int;
    a14: Bool;
    a15: String;
    a16: Int;
    a17: Bool;
    a18: String;
    a19: Int;
    a20: Bool;

    init() {
        self.a1 = 1;
        self.a2 = true;
        self.a3 = "a";
        self.a4 = 4;
        self.a5 = false;
        self.a6 = "b";
        self.a7 = 7;
        self.a8 = true;
        self.a9 = "c";
        self.a10 = 10;
        self.a11 = false;
        self.a12 = "d";
        self.a13 = 13;
        self.a14 = true;
        self.a15 = "e";
        self.a16 = 16;
        self.a17 = false;
        self.a18 = "f";
        self.a19 = 19;
        self.a20 = true;
    }
}