contract BigFields {
    a0: Int = 0;
    a1: Int = 0;
    a2: Int = 0;
    a3: Int = 0;
    a4: Int = 0;
    a5: Int = 0;
    a6: Int = 0;
    a7: Int = 0;
    a8: Int = 0;
    a9: Int = 0;
    b0: Bool = false;
    b1: Bool = false;
    b2: Bool = false;
    b3: Bool = false;
    b4: Bool = false;
    s0: String = "";
    s1: String = "";
    s2: String = "";
    s3: String = "";
    s4: String = "";
    d0: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");
    d1: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");
    d2: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");
    d3: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");
    d4: Address = address("EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c");

    init() {}
}
