contract TestContract {
    bigInt1: Int = 1;
    bigInt2: Int = 2;
    bigInt3: Int = 3;
    bigInt4: Int = 4;
    bigInt5: Int = 5;
    bigInt6: Int = 6;
    bigInt7: Int = 7;
    bigInt8: Int = 8;
    bigInt9: Int = 9;
    bigInt10: Int = 10;
    bigBool1: Bool = true;
    bigBool2: Bool = false;
    bigBool3: Bool = true;
    bigStr1: String = "str1";
    bigStr2: String = "str2";
    bigStr3: String = "str3";

    init() {
        self.bigInt1 = 1;
        self.bigInt2 = 2;
        self.bigInt3 = 3;
        self.bigInt4 = 4;
        self.bigInt5 = 5;
        self.bigInt6 = 6;
        self.bigInt7 = 7;
        self.bigInt8 = 8;
        self.bigInt9 = 9;
        self.bigInt10 = 10;
        self.bigBool1 = true;
        self.bigBool2 = false;
        self.bigBool3 = true;
        self.bigStr1 = "str1";
        self.bigStr2 = "str2";
        self.bigStr3 = "str3";
    }
}