contract ManyFields {
    f1: Int;
    f2: Bool;
    f3: Int?;
    f4: Bool;
    f5: Int;
    f6: Int?;
    f7: Bool;
    f8: Int;
    f9: Bool?;
    f10: Int;
    f11: Int?;
    f12: Bool;
    f13: Int;
    f14: Bool;
    f15: Int?;
    f16: Bool?;

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = null;
        self.f4 = false;
        self.f5 = 5;
        self.f6 = 6;
        self.f7 = true;
        self.f8 = 8;
        self.f9 = null;
        self.f10 = 10;
        self.f11 = null;
        self.f12 = false;
        self.f13 = 13;
        self.f14 = true;
        self.f15 = null;
        self.f16 = null;
    }
}