contract ManyFields {
    f0: Int = 0;
    f1: Int = 0;
    f2: Int = 0;
    f3: Int = 0;
    f4: Int = 0;
    f5: Int = 0;
    f6: Int = 0;
    f7: Int = 0;
    f8: Int = 0;
    f9: Int = 0;
    f10: Int = 0;
    f11: Int = 0;
    f12: Int = 0;
    f13: Int = 0;
    f14: Int = 0;
    f15: Int = 0;
    f16: Int = 0;
    f17: Int = 0;
    f18: Int = 0;
    f19: Int = 0;
    f20: Int = 0;
    f21: Int = 0;
    f22: Int = 0;
    f23: Int = 0;
    f24: Int = 0;
    f25: Int = 0;
    f26: Int = 0;
    f27: Int = 0;
    f28: Int = 0;
    f29: Int = 0;

    init() {}
}