contract VariousDefaults {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Bool = false;
    g: Bool = true;
    h: String = "hello";
    i: String = "world";

    init() {
        self.a = 11;
        self.b = 22;
        self.c = 33;
        self.d = 44;
        self.e = 55;
        self.f = true;
        self.g = false;
        self.h = "hi";
        self.i = "planet";
    }
}