contract ManyFields {
  a1: Int = 1;
  a2: Bool = false;
  a3: String = "x";
  a4: Int = 2;
  a5: Bool = true;
  a6: String = "y";
  a7: Int = 3;
  a8: Bool = false;
  a9: String = "z";
  a10: Int = 4;

  init() {
    self.a1 = 10;
    self.a2 = true;
    self.a3 = "A";
    self.a4 = 20;
    self.a5 = false;
    self.a6 = "B";
    self.a7 = 30;
    self.a8 = true;
    self.a9 = "C";
    self.a10 = 40;
  }
}