contract LongFields {
    f01: Int = 1;
    f02: Int = 2;
    f03: Int = 3;
    f04: Int = 4;
    f05: Int = 5;
    f06: Int = 6;
    f07: Int = 7;
    f08: Int = 8;
    f09: Int = 9;
    f10: Int = 10;
    f11: Int = 11;
    f12: Int = 12;
    f13: Int = 13;
    f14: Int = 14;
    f15: Int = 15;
    f16: Int = 16;
    f17: Int = 17;
    f18: Int = 18;
    f19: Int = 19;
    f20: Int = 20;
    init() {
        self.f01 = 1;

    }
}