contract LargeFlatOptionals {
    a: Int?;
    b: Int?;
    c: Int?;
    d: Int?;
    e: Bool?;
    f: Bool?;
    g: Bool?;
    h: String?;
    i: String?;
    j: Address?;
    k: Address?;
    l: Cell?;
    m: Cell?;
    n: Cell?;

    init() {
        self.a = null; self.b = null; self.c = null; self.d = null;
        self.e = null; self.f = null; self.g = null;
        self.h = null; self.i = null;
        self.j = null; self.k = null;
        self.l = null; self.m = null; self.n = null;
    }
}