contract TestContract {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;
    k: Bool = true;
    l: String = "hello";
    m: Bool? = null;
    n: String? = null;
    o: Int? = null;
    p: Int? = null;

    init() {
        self.a=11; self.b=12; self.c=13; self.d=14; self.e=15; self.f=16;
        self.g=17; self.h=18; self.i=19; self.j=20; self.k=false; self.l="bye";
        self.m=true; self.n="zzz"; self.o=123; self.p=456;
    }
}