contract LongList {
    a: Int;
    b: Bool;
    c: String;
    d: Int;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int;
    k: Bool;
    l: String;
    m: Int;
    n: Bool;
    o: String;

    init() {
        self.a = 1;
        self.b = true;
        self.c = "one";
        self.d = 2;
        self.e = false;
        self.f = "two";
        self.g = 3;
        self.h = true;
        self.i = "three";
        self.j = 4;
        self.k = false;
        self.l = "four";
        self.m = 5;
        self.n = true;
        self.o = "five";
    }
}