contract BulkFields {
    a1: Int;
    a2: Int;
    a3: Int;
    b1: Bool;
    b2: Bool;
    b3: Bool;
    s1: String;
    s2: String;
    s3: String;
    o1: Int?;
    o2: Int?;
    o3: Int?;
    c1: Bool?;
    c2: Bool?;
    c3: Bool?;
    s4: String;
    s5: String;
    s6: String;
    d1: Int;
    d2: Int;

    init() {
        self.a1 = 1;
        self.a2 = 2;
        self.a3 = 3;
        self.b1 = true;
        self.b2 = false;
        self.b3 = true;
        self.s1 = "a";
        self.s2 = "b";
        self.s3 = "c";
        self.o1 = null;
        self.o2 = 77;
        self.o3 = null;
        self.c1 = null;
        self.c2 = true;
        self.c3 = false;
        self.s4 = "x";
        self.s5 = "y";
        self.s6 = "z";
        self.d1 = -1;
        self.d2 = -2;
    }
}