contract Test {
    // 30 persistent variables of alternating type
    v1: Int;
    v2: Bool;
    v3: Int;
    v4: Bool;
    v5: Int;
    v6: Bool;
    v7: Int;
    v8: Bool;
    v9: Int;
    v10: Bool;
    v11: Int;
    v12: Bool;
    v13: Int;
    v14: Bool;
    v15: Int;
    v16: Bool;
    v17: Int;
    v18: Bool;
    v19: Int;
    v20: Bool;
    v21: Int;
    v22: Bool;
    v23: Int;
    v24: Bool;
    v25: Int;
    v26: Bool;
    v27: Int;
    v28: Bool;
    v29: Int;
    v30: Bool;

    init(){
        self.v1=1; self.v2=true; self.v3=2; self.v4=false; self.v5=3; self.v6=true;
        self.v7=4; self.v8=false; self.v9=5; self.v10=true; self.v11=6; self.v12=false;
        self.v13=7; self.v14=true; self.v15=8; self.v16=false; self.v17=9; self.v18=true;
        self.v19=10; self.v20=false; self.v21=11; self.v22=true; self.v23=12; self.v24=false;
        self.v25=13; self.v26=true; self.v27=14; self.v28=false; self.v29=15; self.v30=true;
    }
}
