contract ManyFields {
    f1: Int = 1;
    f2: Bool = true;
    f3: String = "test";
    f4: Int = 4;
    f5: Bool = false;
    f6: String = "six";
    f7: Int = 7;
    f8: Bool = true;
    f9: String = "nine";
    f10: Int = 10;
    f11: Bool = false;
    f12: String = "twelve";

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = "test";
        self.f4 = 4;
        self.f5 = false;
        self.f6 = "six";
        self.f7 = 7;
        self.f8 = true;
        self.f9 = "nine";
        self.f10 = 10;
        self.f11 = false;
        self.f12 = "twelve";
    }
}