contract ManyOptionals {
    a: Int?;
    b: String?;
    c: Bool?;
    d: Int?;
    e: String?;
    f: Bool?;
    g: Int?;
    h: String?;
    i: Bool?;
    j: Int?;

    init() {
        self.a = 1;
        self.b = null;
        self.c = true;
        self.d = null;
        self.e = "abc";
        self.f = false;
        self.g = null;
        self.h = "def";
        self.i = true;
        self.j = 99;
    }
}