contract LargeOptionalMix {
    a: Int?;
    b: Address?;
    c: Cell?;
    d: String?;
    e: Bool?;
    f: Int?;
    g: Address?;
    h: Cell?;
    i: String?;
    j: Bool?;

    init() {
        self.a = null;
        self.b = null;
        self.c = null;
        self.d = null;
        self.e = null;
        self.f = null;
        self.g = null;
        self.h = null;
        self.i = null;
        self.j = null;
    }
}