contract LargePersistent {
    a: Int = 0;
    b: Bool = false;
    c: Int = 1;
    d: Bool = true;
    e: Int = 2;
    f: Bool = false;
    g: Int = 3;
    h: Bool = true;
    i: Int = 4;
    j: Bool = false;
    k: Int = 5;
    l: Bool = true;
    m: Int = 6;
    n: Bool = false;
    o: Int = 7;
    p: Bool = true;
    q: Int = 8;
    r: Bool = false;
    s: Int = 9;
    t: Bool = true;
    u: Int = 10;
    v: Bool = false;
    w: Int = 11;
    x: Bool = true;
    y: Int = 12;
    z: Bool = false;
    init() {}
}