contract LongContract {
    val1: Int;
    val2: Bool;
    val3: Int;
    val4: Bool;
    val5: String;
    val6: Int;
    val7: String;
    val8: Bool;
    val9: Int;
    val10: Bool;
    val11: String;
    val12: Int;
    val13: String;
    val14: Bool;
    val15: Int;
    val16: String;
    val17: Bool;
    val18: Int;
    val19: Int;
    val20: Bool;

    init() {
        self.val1 = 1;
        self.val2 = true;
        self.val3 = 3;
        self.val4 = false;
        self.val5 = "five";
        self.val6 = 6;
        self.val7 = "seven";
        self.val8 = true;
        self.val9 = 9;
        self.val10 = false;
        self.val11 = "eleven";
        self.val12 = 12;
        self.val13 = "thirteen";
        self.val14 = true;
        self.val15 = 15;
        self.val16 = "sixteen";
        self.val17 = false;
        self.val18 = 18;
        self.val19 = 19;
        self.val20 = true;
    }
}