contract TestContract {
    f1: Int = 1; f2: Int = 2; f3: Int = 3; f4: Int = 4; f5: Int = 5;
    f6: Int = 6; f7: Int = 7; f8: Int = 8; f9: Int = 9; f10: Int = 10;
    f11: Int = 11; f12: Int = 12; f13: Int = 13; f14: Int = 14; f15: Int = 15;
    f16: Int = 16; f17: Int = 17; f18: Int = 18; f19: Int = 19; f20: Int = 20;
    f21: Int = 21; f22: Int = 22; f23: Int = 23; f24: Int = 24; f25: Int = 25;
    f26: Int = 26; f27: Int = 27; f28: Int = 28; f29: Int = 29; f30: Int = 30;
}