contract ManyFields {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool;
    f: String;
    g: Int;
    h: String;
    i: Bool;
    j: Int;
    k: String;
    l: Bool;
    m: Int?;
    n: String;
    o: Bool;
    p: Int;

    init() {
        self.a = 1;
        self.b = false;
        self.c = "1";
        self.d = null;
        self.e = true;
        self.f = "f";
        self.g = 7;
        self.h = "h";
        self.i = true;
        self.j = 10;
        self.k = "k";
        self.l = false;
        self.m = null;
        self.n = "n";
        self.o = true;
        self.p = 42;
    }
}