struct LooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName {
    a: Int;
    b: Bool;
}

contract LongNames {
    x: LooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName;
    
    init() {
        self.x = LooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongName{
            a: 42,
            b: true
        };
    }
}
