contract ManyOptionalBools {
  a: Bool?; b: Bool?; c: Bool?; d: Bool?; e: Bool?;
  f: Bool?; g: Bool?; h: Bool?; i: Bool?; j: Bool?;
  k: Bool?; l: Bool?; m: Bool?; n: Bool?; o: Bool?;
  p: Bool?; q: Bool?; r: Bool?; s: Bool?; t: Bool?;

  init() {
    self.a = null; self.b = null; self.c = null; self.d = null; self.e = null;
    self.f = null; self.g = null; self.h = null; self.i = null; self.j = null;
    self.k = null; self.l = null; self.m = null; self.n = null; self.o = null;
    self.p = null; self.q = null; self.r = null; self.s = null; self.t = null;
  }
}