contract TestLongDefaults {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;
    k: Int = 11;
    l: Int = 12;
    m: Int = 13;
    n: Int = 14;
    o: Int = 15;
    p: Int = 16;
    q: Int = 17;
    r: Int = 18;
    s: Int = 19;
    t: Int = 20;

    init() {
        self.a = 2;
        self.b = 3;
        self.c = 4;
        self.d = 5;
        self.e = 6;
        self.f = 7;
        self.g = 8;
        self.h = 9;
        self.i = 10;
        self.j = 11;
        self.k = 12;
        self.l = 13;
        self.m = 14;
        self.n = 15;
        self.o = 16;
        self.p = 17;
        self.q = 18;
        self.r = 19;
        self.s = 20;
        self.t = 21;
    }
}
