contract LargeContractWithOptions {
    f1: Int?;
    f2: Int?;
    f3: Int?;
    f4: Int?;
    f5: Int?;
    f6: String;
    f7: String;
    f8: Bool;
    f9: Bool;
    f10: String;

    init() {
        self.f1 = 1;
        self.f2 = 2;
        self.f3 = null;
        self.f4 = null;
        self.f5 = 5;
        self.f6 = "a";
        self.f7 = "b";
        self.f8 = true;
        self.f9 = false;
        self.f10 = "c";
    }
}