contract LongListOptional {
    a: Int?;
    b: Int?;
    c: Int?;
    d: Int?;
    e: Int?;
    f: Int?;
    g: Int?;
    h: Int?;
    i: Int?;
    j: Int?;
    k: Int?;
    l: Int?;
    m: Int?;
    n: Int?;
    o: Int?;
    p: Int?;
    q: Int?;
    r: Int?;
    s: Int?;
    t: Int?;

    init() {
        self.a = null;
        self.b = 1;
        self.c = null;
        self.d = 2;
        self.e = null;
        self.f = 3;
        self.g = null;
        self.h = 4;
        self.i = null;
        self.j = 5;
        self.k = null;
        self.l = 6;
        self.m = null;
        self.n = 7;
        self.o = null;
        self.p = 8;
        self.q = null;
        self.r = 9;
        self.s = null;
        self.t = 10;
    }
}