contract LongFieldList {
    a: Int;
    b: Bool;
    c: String;
    d: Int;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int;
    k: Bool;
    l: String;
    m: Int;
    n: Bool;
    o: String;
    p: Int;
    q: Bool;
    r: String;
    s: Int;
    t: Bool;
    
    init() {
        self.a = 1;
        self.b = true;
        self.c = "c";
        self.d = 4;
        self.e = false;
        self.f = "f";
        self.g = 7;
        self.h = true;
        self.i = "i";
        self.j = 10;
        self.k = true;
        self.l = "l";
        self.m = 13;
        self.n = false;
        self.o = "o";
        self.p = 16;
        self.q = true;
        self.r = "r";
        self.s = 19;
        self.t = false;
    }
}