contract LargeOptional {
    a: Int?;
    b: Bool?;
    c: String?;
    d: Slice?;
    e: Cell?;
    f: Int?;
    g: Bool?;
    h: String?;
    i: Slice?;
    j: Cell?;
    k: Int?;
    l: Bool?;
    m: String?;
    n: Slice?;
    o: Cell?;

    init() {
        self.a = null;
        self.b = null;
        self.c = null;
        self.d = null;
        self.e = null;
        self.f = null;
        self.g = null;
        self.h = null;
        self.i = null;
        self.j = null;
        self.k = null;
        self.l = null;
        self.m = null;
        self.n = null;
        self.o = null;
    }
}