contract TestContract {
    f1: Int = 0;
    f2: Bool = false;
    f3: Int = 0;
    f4: Bool = false;
    f5: Int = 0;
    f6: Bool = false;
    f7: Int = 0;
    f8: Bool = false;
    f9: Int = 0;
    f10: Bool = false;
    f11: Int = 0;
    f12: Bool = false;
    f13: Int = 0;
    f14: Bool = false;
    f15: Int = 0;
    f16: Bool = false;

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = 2;
        self.f4 = true;
        self.f5 = 3;
        self.f6 = true;
        self.f7 = 4;
        self.f8 = true;
        self.f9 = 5;
        self.f10 = true;
        self.f11 = 6;
        self.f12 = true;
        self.f13 = 7;
        self.f14 = true;
        self.f15 = 8;
        self.f16 = true;
    }
}
