contract LargeFlat {
    a: Int as uint8;
    b: Int as uint16;
    c: Int as uint32;
    d: Int as uint64;
    e: Int as uint128;
    f: Int as uint256;
    g: Bool;
    h: Bool;
    i: Bool;
    j: Bool;
    k: Bool;
    l: Bool;
    m: Bool;
    n: Bool;
    o: Bool;
    p: Bool;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = 4;
        self.e = 5;
        self.f = 6;
        self.g = true;
        self.h = false;
        self.i = true;
        self.j = false;
        self.k = true;
        self.l = false;
        self.m = true;
        self.n = false;
        self.o = true;
        self.p = false;
    }
}