contract LongPersistentList {
    a: Int = 1;
    b: Bool = true;
    c: String = "c";
    d: Int = 4;
    e: Bool = false;
    f: String = "f";
    g: Int = 7;
    h: Bool = true;
    i: String = "i";
    j: Int = 10;
    k: Bool = false;
    l: String = "l";
    m: Int = 13;
    n: Bool = true;
    o: String = "o";
    p: Int = 16;
    q: Bool = false;
    r: String = "r";
    s: Int = 19;
    t: Bool = true;
    u: String = "u";
    v: Int = 22;
    w: Bool = false;
    x: String = "x";
    y: Int = 25;
    z: Bool = true;

    init() {
        self.a=100; self.b=false; self.c="C";
        self.d=101; self.e=true;  self.f="F";
        self.g=102; self.h=false; self.i="I";
        self.j=103; self.k=true;  self.l="L";
        self.m=104; self.n=false; self.o="O";
        self.p=105; self.q=true;  self.r="R";
        self.s=106; self.t=false; self.u="U";
        self.v=107; self.w=true;  self.x="X";
        self.y=108; self.z=false;
    }
}
