contract LargeBoolOptions {
    b1: Bool?; b2: Bool?; b3: Bool?; b4: Bool?;
    b5: Bool?; b6: Bool?; b7: Bool?; b8: Bool?;
    b9: Bool?; b10: Bool?; b11: Bool?; b12: Bool?;

    init() {
        self.b1 = true; self.b2 = false; self.b3 = null; self.b4 = false;
        self.b5 = null; self.b6 = true; self.b7 = null; self.b8 = true;
        self.b9 = false; self.b10 = null; self.b11 = true; self.b12 = false;
    }
}