contract LargeStrings {
  a: String = "a";
  b: String = "b";
  c: String = "c";
  d: String = "d";
  e: String = "e";
  f: String = "f";
  g: String = "g";
  h: String = "h";
  i: String = "i";
  j: String = "j";

  init() {
    self.a = "A";
    self.b = "B";
    self.c = "C";
    self.d = "D";
    self.e = "E";
    self.f = "F";
    self.g = "G";
    self.h = "H";
    self.i = "I";
    self.j = "J";
  }
}