contract LongBoolList {
    b0: Bool = true;
    b1: Bool = false;
    b2: Bool = true;
    b3: Bool = false;
    b4: Bool = true;
    b5: Bool = false;
    b6: Bool = true;
    b7: Bool = false;
    b8: Bool = true;
    b9: Bool = false;
    b10: Bool = true;
    b11: Bool = false;
    b12: Bool = true;
    b13: Bool = false;
    b14: Bool = true;
    b15: Bool = false;
    b16: Bool = true;
    b17: Bool = false;
    b18: Bool = true;
    b19: Bool = false;

    init() {}
}
