contract LongFieldList {
    f1: Int;
    f2: String;
    f3: Int;
    f4: Bool;
    f5: Int;
    f6: Bool?;
    f7: Int?;
    f8: String?;
    f9: Bool;
    f10: Int;
    f11: String;
    f12: Bool?;
    f13: Int?;
    f14: String?;
    f15: Bool;
    f16: Int;
    f17: String;
    f18: Bool?;
    f19: Int?;
    f20: String?;

    init() {
        self.f1 = 1;
        self.f2 = "a";
        self.f3 = 3;
        self.f4 = true;
        self.f5 = 5;
        self.f6 = null;
        self.f7 = 7;
        self.f8 = null;
        self.f9 = false;
        self.f10 = 10;
        self.f11 = "b";
        self.f12 = true;
        self.f13 = null;
        self.f14 = null;
        self.f15 = false;
        self.f16 = 16;
        self.f17 = "c";
        self.f18 = null;
        self.f19 = null;
        self.f20 = "d";
    }
}