contract LotsDefaults {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Bool = true;
    e: Bool = false;
    f: String = "a";
    g: String = "b";
    h: Int = 4;
    i: Int = 5;
    j: Bool = true;
    k: String = "c";
    l: Bool = false;
    m: Int = 6;
    n: Bool = true;
    o: String = "d";
    p: Int = 7;
    q: String = "e";
    r: Bool = false;
    s: Int = 8;
    t: String = "f";

    init() {
        self.a=1; self.b=2; self.c=3; self.d=true; self.e=false;
        self.f="a"; self.g="b"; self.h=4; self.i=5; self.j=true;
        self.k="c"; self.l=false; self.m=6; self.n=true; self.o="d";
        self.p=7; self.q="e"; self.r=false; self.s=8; self.t="f";
    }
}