contract LongFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool;
    e: Int; 
    f: Bool;
    g: Int?;
    h: Bool;
    i: Int;
    j: Bool;
    k: Int?;
    l: Bool;
    m: Int;
    n: Bool;
    o: Int?;
    p: Bool;
    q: Int;
    r: Bool;
    s: Int?;
    t: Bool;
    init() {
        self.a = 1; self.b = true; self.c = null; self.d = false;
        self.e = 2; self.f = true; self.g = null; self.h = false;
        self.i = 3; self.j = true; self.k = null; self.l = false;
        self.m = 4; self.n = true; self.o = null; self.p = false;
        self.q = 5; self.r = true; self.s = null; self.t = false;
    }
}