contract ManyOptionalStrings {
    a: String?;
    b: String?;
    c: String?;
    d: String?;
    e: String?;
    f: String?;
    g: String?;
    h: String?;
    i: String?;
    j: String?;
    k: String?;
    l: String?;
    m: String?;
    n: String?;
    o: String?;
    p: String?;
    init() {
        self.a=null; self.b=null; self.c=null; self.d=null;
        self.e=null; self.f=null; self.g=null; self.h=null;
        self.i=null; self.j=null; self.k=null; self.l=null;
        self.m=null; self.n=null; self.o=null; self.p=null;
    }
}
