contract LargeOpt {
    o1: Int? = null;
    o2: Int? = null;
    o3: Int? = null;
    o4: Int? = null;
    o5: Int? = null;
    o6: Int? = null;
    o7: Int? = null;
    o8: Int? = null;
    o9: Int? = null;
    o10: Int? = null;

    init() {
        self.o1=1;
        self.o2=2;
        self.o3=3;
        self.o4=4;
        self.o5=5;
        self.o6=6;
        self.o7=7;
        self.o8=8;
        self.o9=9;
        self.o10=10;
    }
}