contract CompressionTest {
    a: Bool;
    b: Bool;
    c: Bool;
    d: Bool;
    e: Bool;
    f: Bool;
    g: Bool;
    h: Bool;
    i: Bool;
    j: Bool;
    k: Bool;
    l: Bool;
    m: Bool;
    n: Bool;
    o: Bool;
    p: Bool;
    q: Bool;
    r: Bool;
    s: Bool;
    t: Bool;

    init() {
        self.a=false; self.b=true; self.c=false; self.d=true; self.e=false;
        self.f=false; self.g=true; self.h=false; self.i=true; self.j=false;
        self.k=false; self.l=true; self.m=false; self.n=true; self.o=false;
        self.p=false; self.q=true; self.r=true; self.s=false; self.t=true;
    }
}