contract LongList {
    n1: Int = 1;
    n2: Int = 2;
    n3: Int = 3;
    n4: Int = 4;
    n5: Int = 5;
    n6: Int = 6;
    n7: Int = 7;
    n8: Int = 8;
    n9: Int = 9;
    n10: Int = 10;
    n11: Int = 11;
    n12: Int = 12;
    n13: Int = 13;
    n14: Int = 14;
    n15: Int = 15;
    n16: Int = 16;
    n17: Int = 17;
    n18: Int = 18;
    n19: Int = 19;
    n20: Int = 20;
    n21: Int = 21;
    n22: Int = 22;
    n23: Int = 23;
    n24: Int = 24;
    n25: Int = 25;

    init() {
        self.n25 = 125;
    }
}