contract ManyFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: String;
    e: Bool?;
    f: Int;
    g: String;
    h: Int?;
    i: Bool;
    j: String;
    k: Int;
    l: Bool?;
    m: String;
    n: Int?;
    o: Bool;

    init() {
        self.a = 1;
        self.b = false;
        self.c = null;
        self.d = "d";
        self.e = null;
        self.f = 6;
        self.g = "g";
        self.h = null;
        self.i = true;
        self.j = "j";
        self.k = 11;
        self.l = null;
        self.m = "m";
        self.n = null;
        self.o = true;
    }
}