contract LargeFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool;
    e: Int;
    f: Int?;
    g: Bool;
    h: Int;
    i: Bool;
    j: Int?;
    k: Int;
    l: Bool;
    m: Int?;
    n: Int;
    o: Bool;
    p: Int?;
    q: Int;
    r: Bool;
    s: Int?;
    t: Int;

    init() {
        self.a = 1;
        self.b = true;
        self.c = null;
        self.d = false;
        self.e = 5;
        self.f = 6;
        self.g = true;
        self.h = 8;
        self.i = false;
        self.j = null;
        self.k = 11;
        self.l = true;
        self.m = 12;
        self.n = 13;
        self.o = false;
        self.p = null;
        self.q = 17;
        self.r = true;
        self.s = null;
        self.t = 20;
    }
}