contract ManyFields {
    f1: Int;
    f2: Int;
    f3: Bool;
    f4: Bool;
    f5: String;
    f6: Int;
    f7: Bool;
    f8: String;
    f9: Int;
    f10: String;

    init() {
        self.f1 = 1;
        self.f2 = 2;
        self.f3 = true;
        self.f4 = false;
        self.f5 = "hi";
        self.f6 = 6;
        self.f7 = true;
        self.f8 = "test";
        self.f9 = 9;
        self.f10 = "end";
    }
}