contract Test9 {
  manyInts0: Int = 0;
  manyInts1: Int = 1;
  manyInts2: Int = 2;
  manyInts3: Int = 3;
  manyInts4: Int = 4;
  manyInts5: Int = 5;
  manyInts6: Int = 6;
  manyInts7: Int = 7;
  manyInts8: Int = 8;
  manyInts9: Int = 9;
  manyInts10: Int = 10;
  manyInts11: Int = 11;
  manyInts12: Int = 12;
  manyInts13: Int = 13;
  manyInts14: Int = 14;
  manyInts15: Int = 15;
  manyInts16: Int = 16;
  manyInts17: Int = 17;
  manyInts18: Int = 18;
  manyInts19: Int = 19;

  init() {}
}