contract Test8 {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;

    init() {
        self.a = 10;
        self.b = 9;
        self.c = 8;
        self.d = 7;
        self.e = 6;
        self.f = 5;
        self.g = 4;
        self.h = 3;
        self.i = 2;
        self.j = 1;
    }
}