contract TestContract {
    zero: Int = 0;
    one: Int = 1;
    two: Int = 2;
    three: Int = 3;
    four: Int = 4;
    five: Int = 5;
    six: Int = 6;
    seven: Int = 7;
    eight: Int = 8;
    nine: Int = 9;

    init() {
      self.zero = 0;
      self.one = 1;
      self.two = 2;
      self.three = 3;
      self.four = 4;
      self.five = 5;
      self.six = 6;
      self.seven = 7;
      self.eight = 8;
      self.nine = 9;
    }
}