contract TestContract {
    f01: Int as uint8 = 0;
    f02: Int as uint8 = 1;
    f03: Int as uint8 = 2;
    f04: Int as uint8 = 3;
    f05: Int as uint8 = 4;
    f06: Int as uint8 = 5;
    f07: Int as uint8 = 6;
    f08: Int as uint8 = 7;
    f09: Int as uint8 = 8;
    f10: Int as uint8 = 9;
    f11: Int as uint8 = 10;
    f12: Int as uint8 = 11;
    f13: Int as uint8 = 12;
    f14: Int as uint8 = 13;
    f15: Int as uint8 = 14;

    init() {
        self.f01=1; self.f02=2; self.f03=3; self.f04=4; self.f05=5;
        self.f06=6; self.f07=7; self.f08=8; self.f09=9; self.f10=10;
        self.f11=11; self.f12=12; self.f13=13; self.f14=14; self.f15=15;
    }
}