contract TestManyFields {
    a: Int = 0;
    b: Int = 1;
    c: Int = 2;
    d: Int = 3;
    e: Int = 4;
    f: Int = 5;
    g: Int = 6;
    h: Int = 7;
    i: Int = 8;
    j: Int = 9;
    k: Int = 10;
    l: Int = 11;
    m: Int = 12;
    n: Int = 13;
    o: Int = 14;
    p: Int = 15;
    q: Int = 16;
    r: Int = 17;
    s: Int = 18;
    t: Int = 19;
    u: Int = 20;
    v: Int = 21;
    w: Int = 22;
    x: Int = 23;
    y: Int = 24;
    z: Int = 25;

    init() {
        self.a = 0; self.b = 1; self.c = 2; self.d = 3;
        self.e = 4; self.f = 5; self.g = 6; self.h = 7;
        self.i = 8; self.j = 9; self.k = 10; self.l = 11;
        self.m = 12; self.n = 13; self.o = 14; self.p = 15;
        self.q = 16; self.r = 17; self.s = 18; self.t = 19;
        self.u = 20; self.v = 21; self.w = 22; self.x = 23;
        self.y = 24; self.z = 25;
    }
}