contract LongTupleFields {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Int;
    f: Int;
    g: Int;
    h: Int;
    i: Int;
    j: Int;
    k: Int;
    l: Int;
    m: Int;
    n: Int;
    o: Int;
    p: Int;

    init() {
      self.a=1; self.b=2; self.c=3; self.d=4;
      self.e=5; self.f=6; self.g=7; self.h=8;
      self.i=9; self.j=10; self.k=11; self.l=12;
      self.m=13; self.n=14; self.o=15; self.p=16;
    }
}