contract ManyFields {
    a: Int;
    b: Bool;
    c: Int?;
    d: String;
    e: Bool;
    f: String?;
    g: Int;
    h: Bool?;
    i: String;
    j: Int;
    k: Bool;
    l: Int?;
    m: Bool?;
    n: String?;
    o: Int;
    p: Bool;

    init() {
        self.a = 1;
        self.b = true;
        self.c = null;
        self.d = "d";
        self.e = false;
        self.f = null;
        self.g = 7;
        self.h = null;
        self.i = "i";
        self.j = 10;
        self.k = true;
        self.l = null;
        self.m = null;
        self.n = null;
        self.o = 15;
        self.p = false;
    }
}
