contract ManyFields {
  a: Int;
  b: Bool;
  c: String;
  d: Int;
  e: Bool;
  f: String;
  g: Int;
  h: Bool;
  i: String;
  j: Int;
  k: Bool;
  l: String;
  m: Int;
  n: Bool;
  o: String;
  p: Int;
  q: Bool;
  r: String;
  s: Int;
  t: Bool;

  init() {
    self.a=1; self.b=true; self.c="a"; self.d=2; self.e=false;
    self.f="b"; self.g=3; self.h=true; self.i="c"; self.j=4;
    self.k=false; self.l="d"; self.m=5; self.n=true; self.o="e";
    self.p=6; self.q=false; self.r="f"; self.s=7; self.t=true;
  }
}