contract LargeFields {
    f1: Int = 1;
    f2: Int = 2;
    f3: Int = 3;
    f4: Int = 4;
    f5: Int = 5;
    f6: Int = 6;
    f7: Int = 7;
    f8: Int = 8;
    f9: Int = 9;
    f10: Int = 10;
    f11: Int = 11;
    f12: Int = 12;
    f13: Int = 13;
    f14: Int = 14;
    f15: Int = 15;
    f16: Int = 16;
    init() {
        self.f1 = 101;
        self.f2 = 102;
        self.f3 = 103;
        self.f4 = 104;
        self.f5 = 105;
        self.f6 = 106;
        self.f7 = 107;
        self.f8 = 108;
        self.f9 = 109;
        self.f10 = 110;
        self.f11 = 111;
        self.f12 = 112;
        self.f13 = 113;
        self.f14 = 114;
        self.f15 = 115;
        self.f16 = 116;
    }
}
