contract LargeManyFields {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Int;
    f: Int;
    g: Int;
    h: Int;
    i: Int;
    j: Int;
    k: Int;
    l: Int;
    m: Int;
    n: Int;
    o: Int;
    p: Int;
    q: Int;
    r: Int;
    s: Int;
    t: Int;
    u: Int;
    v: Int;
    w: Int;
    x: Int;
    y: Int;
    z: Int;

    init() {
        self.a=0; self.b=1; self.c=2; self.d=3;
        self.e=4; self.f=5; self.g=6; self.h=7;
        self.i=8; self.j=9; self.k=10; self.l=11;
        self.m=12; self.n=13; self.o=14; self.p=15;
        self.q=16; self.r=17; self.s=18; self.t=19;
        self.u=20; self.v=21; self.w=22; self.x=23;
        self.y=24; self.z=25;
    }
}
