contract Test5 {
    n1: Int = 1;
    n2: Int = 2;
    n3: Int = 3;
    n4: Int = 4;
    n5: Int = 5;
    n6: Int = 6;
    n7: Int = 7;
    n8: Int = 8;
    n9: Int = 9;
    n10: Int = 10;

    init() {
        self.n1 = 1;
        self.n2 = 2;
        self.n3 = 3;
        self.n4 = 4;
        self.n5 = 5;
        self.n6 = 6;
        self.n7 = 7;
        self.n8 = 8;
        self.n9 = 9;
        self.n10 = 10;
    }
}