contract BigFields {
    f1: Int;
    f2: Int;
    f3: Int;
    f4: Bool;
    f5: Bool;
    f6: Int;
    f7: Bool;
    f8: Int;
    f9: Bool;
    f10: Int;

    init() {
        self.f1 = 1;
        self.f2 = 2;
        self.f3 = 3;
        self.f4 = true;
        self.f5 = false;
        self.f6 = 6;
        self.f7 = true;
        self.f8 = 8;
        self.f9 = false;
        self.f10 = 10;
    }
}