// contract with large number of optional Int fields to test serialization limits
contract BigOpt {
    a: Int? = null;
    b: Int? = null;
    c: Int? = null;
    d: Int? = null;
    e: Int? = null;
    f: Int? = null;
    g: Int? = null;
    h: Int? = null;
    i: Int? = null;
    j: Int? = null;
    k: Int? = null;
    l: Int? = null;
    m: Int? = null;
    n: Int? = null;
    o: Int? = null;
    p: Int? = null;
    q: Int? = null;
    r: Int? = null;
    s: Int? = null;
    t: Int? = null;
    u: Int? = null;
    v: Int? = null;
    w: Int? = null;
    x: Int? = null;
    y: Int? = null;
    z: Int? = null;
    init() {}
}