contract LargeContract {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool?;
    f: String?;
    g: Int;
    h: Bool;
    i: String;
    j: Int?;
    k: Bool?;
    l: String?;
    m: Int;
    n: Bool;
    o: String;

    init() {
        self.a=1; self.b=false; self.c="hi";
        self.d=null; self.e=null; self.f=null;
        self.g=2; self.h=true; self.i="hello";
        self.j=null; self.k=null; self.l=null;
        self.m=3; self.n=true; self.o="bye";
    }
}
