contract LargeOptionals {
    a0:Int?; a1:Int?; a2:Int?; a3:Int?; a4:Int?;
    a5:Int?; a6:Int?; a7:Int?; a8:Int?; a9:Int?;
    a10:Int?; a11:Int?; a12:Int?; a13:Int?; a14:Int?;
    a15:Int?; a16:Int?; a17:Int?; a18:Int?; a19:Int?;

    init() {
        self.a0=null; self.a1=1; self.a2=null; self.a3=3; self.a4=null;
        self.a5=5; self.a6=null; self.a7=7; self.a8=null; self.a9=9;
        self.a10=null; self.a11=11; self.a12=null; self.a13=13; self.a14=null;
        self.a15=15; self.a16=null; self.a17=17; self.a18=null; self.a19=19;
    }
}