contract Test {
    a0: Int?;
    a1: Bool;
    a2: Int?;
    a3: Bool;
    a4: Int?;
    a5: Bool;
    a6: Int?;
    a7: Bool;
    a8: Int?;
    a9: Bool;
    a10: Int?;
    a11: Bool;
    a12: Int?;
    a13: Bool;
    a14: Int?;
    a15: Bool;

    init() {
        self.a0 = null;    self.a1 = true;
        self.a2 = null;    self.a3 = false;
        self.a4 = null;    self.a5 = true;
        self.a6 = null;    self.a7 = false;
        self.a8 = null;    self.a9 = true;
        self.a10 = null;   self.a11 = false;
        self.a12 = null;   self.a13 = true;
        self.a14 = null;   self.a15 = false;
    }
}