contract LargeFieldList {
    a1: Int; a2: Int; a3: Int; a4: Int; a5: Int; a6: Int; a7: Int; a8: Int; a9: Int; a10: Int;
    b1: Bool; b2: Bool; b3: Bool; b4: Bool; b5: Bool; b6: Bool; b7: Bool; b8: Bool; b9: Bool; b10: Bool;
    s1: String; s2: String; s3: String; s4: String; s5: String; s6: String; s7: String; s8: String; s9: String; s10: String;

    init() {
        self.a1 = 1; self.a2 = 2; self.a3 = 3; self.a4 = 4; self.a5 = 5; self.a6 =6; self.a7=7; self.a8=8; self.a9=9; self.a10=10;
        self.b1 = true; self.b2=false; self.b3=true; self.b4=false; self.b5=true; self.b6=false; self.b7=true; self.b8=false; self.b9=true; self.b10=false;
        self.s1= "1"; self.s2= "2"; self.s3="3"; self.s4="4"; self.s5="5"; self.s6="6"; self.s7="7"; self.s8="8"; self.s9="9"; self.s10="10";
    }
}