contract LongListStorage {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int?;
    f5: String?;
    f6: Bool?;
    f7: Int;
    f8: Bool;
    f9: String;
    f10: Int?;
    f11: Bool?;
    f12: Int;

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = "hi";
        self.f4 = null;
        self.f5 = "x";
        self.f6 = null;
        self.f7 = 7;
        self.f8 = false;
        self.f9 = "end";
        self.f10 = 10;
        self.f11 = null;
        self.f12 = 12;
    }
}