contract LargeManyPrimitives {
    a: Int;
    b: Bool;
    c: Int?;
    d: Bool;
    e: Int;
    f: Bool;
    g: Int?;
    h: Bool;
    i: Int;
    j: Bool;
    k: Int?;
    l: Bool;
    m: Int;
    n: Bool;
    o: Int?;
    p: Bool;
    q: Int;
    r: Bool;

    init() {
        self.a = 1;
        self.b = false;
        self.c = null;
        self.d = true;
        self.e = 5;
        self.f = false;
        self.g = 6;
        self.h = true;
        self.i = 9;
        self.j = false;
        self.k = null;
        self.l = true;
        self.m = 20;
        self.n = false;
        self.o = 30;
        self.p = true;
        self.q = 50;
        self.r = false;
    }
}
