contract ManyFields {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int?;

    init() {
        self.a = 1;
        self.b = true;
        self.c = "str";
        self.d = null;
        self.e = false;
        self.f = "str2";
        self.g = 2;
        self.h = true;
        self.i = "str3";
        self.j = 5;
    }
}