contract BigContract {
    a: Int;
    b: Bool;
    c: String;
    d: Int?;
    e: Bool?;
    f: String;
    g: Int;
    h: Bool;
    i: String?;
    j: Int;
    init() {
        self.a = 1;
        self.b = true;
        self.c = "str";
        self.d = null;
        self.e = null;
        self.f = "test";
        self.g = 7;
        self.h = false;
        self.i = null;
        self.j = 10;
    }
}