contract WideStorage {
    item1: Int = 1;
    item2: Int = 2;
    item3: Int = 3;
    item4: Int = 4;
    item5: Int = 5;
    item6: Int = 6;
    item7: Int = 7;
    item8: Int = 8;
    item9: Int = 9;
    item10: Int = 10;
    item11: Int = 11;
    item12: Int = 12;
    item13: Int = 13;
    item14: Int = 14;
    item15: Int = 15;
    item16: Int = 16;

    init() {
        self.item1 = 101;
        self.item16 = 222;
    }
}
