contract ManyVars {
    a1: Int;
    a2: Int;
    a3: Int;
    a4: Int;
    a5: Int;
    a6: Int;
    a7: Int;
    a8: Int;
    a9: Int;
    a10: Int;
    a11: Bool;
    a12: Bool;
    a13: Bool;
    a14: Bool;
    a15: Bool;
    a16: Bool;
    a17: Bool;
    a18: Bool;
    a19: Bool;
    a20: Bool;
    b1: Int?;
    b2: Int?;
    b3: Int?;
    b4: Int?;
    b5: Int?;
    b6: String?;
    b7: String?;
    b8: String?;
    b9: String?;
    b10: String?;
    b11: Int?;
    b12: Int?;
    b13: Int?;
    b14: Int?;
    b15: Int?;
    b16: String?;
    b17: String?;
    b18: String?;
    b19: String?;
    b20: String?;

    init() {
        self.a1 = 1; self.a2=2; self.a3=3; self.a4=4; self.a5=5; self.a6=6; self.a7=7; self.a8=8; self.a9=9; self.a10=10;
        self.a11=true; self.a12=false; self.a13=true; self.a14=false; self.a15=true; self.a16=false; self.a17=true; self.a18=false; self.a19=true; self.a20=false;
        self.b1=null; self.b2=null; self.b3=null; self.b4=null; self.b5=null;
        self.b6=null; self.b7=null; self.b8=null; self.b9=null; self.b10=null;
        self.b11=null; self.b12=null; self.b13=null; self.b14=null; self.b15=null;
        self.b16=null; self.b17=null; self.b18=null; self.b19=null; self.b20=null;
    }
}