contract BigPrimitiveList {
    a: Int;
    b: Bool;
    c: String;
    d: Int;
    e: Bool;
    f: String;
    g: Int;
    h: Bool;
    i: String;
    j: Int;
    k: Bool;
    l: String;

    init() {
        self.a = 0;
        self.b = false;
        self.c = "c";
        self.d = 0;
        self.e = false;
        self.f = "f";
        self.g = 0;
        self.h = false;
        self.i = "i";
        self.j = 0;
        self.k = false;
        self.l = "l";
    }
}