contract TestContract {
    a: Int = 1;
    b: Int as uint8 = 2;
    c: Bool = true;
    d: String = "d";
    e: Int as int16 = 3;
    f: Bool = false;
    g: Int as uint32 = 4;
    h: String = "h";
    i: Int = 5;
    j: Int as int32 = 6;
    k: Bool = true;
    l: Int as uint16 = 7;
    m: String = "m";
    n: Bool = false;
    o: Int as uint64 = 8;
    p: String = "p";
    q: Int = 9;
    r: Int as int64 = 10;
    s: Bool = true;
    t: String = "t";

    init() {}
}