// very wide contract storage
contract Wide {
    a: Int;
    b: Int;
    c: Int;
    d: Int;
    e: Bool;
    f: String;
    g: Int?;
    h: String?;
    i: Bool?;
    j: Int;
    k: Bool;
    l: String;

    init() {
        self.a = 1;
        self.b = 2;
        self.c = 3;
        self.d = 4;
        self.e = true;
        self.f = "hi";
        self.g = null;
        self.h = null;
        self.i = null;
        self.j = 10;
        self.k = false;
        self.l = "end";
    }
}