struct BigOpt {
    f1: Int?;
    f2: Int?;
    f3: Int?;
    f4: Int?;
    f5: Int?;
    f6: Int?;
    f7: Int?;
    f8: Int?;
    f9: Int?;
    f10: Int?;
    f11: Int?;
    f12: Int?;
    f13: Int?;
    f14: Int?;
    f15: Int?;
}

contract BigPersistent {
    s: BigOpt = BigOpt{
        f1: 1, f2: null, f3: 3, f4: null, f5: 5, f6: null, f7: 7, f8: null,
        f9: 9, f10: null, f11: 11, f12: null, f13: 13, f14: null, f15: 15
    };
}