contract ExtremeStorage {
    f01: Int; f02: Int; f03: Int; f04: Int; f05: Int; f06: Int; f07: Int; f08: Int; f09: Int; f10: Int;
    f11: Int; f12: Int; f13: Int; f14: Int; f15: Int; f16: Int; f17: Int; f18: Int; f19: Int; f20: Int;
    f21: Int; f22: Int; f23: Int; f24: Int; f25: Int; f26: Int; f27: Int; f28: Int; f29: Int; f30: Int;
    f31: Int; f32: Int; f33: Int; f34: Int; f35: Int; f36: Int; f37: Int; f38: Int; f39: Int; f40: Int;
    f41: Int; f42: Int; f43: Int; f44: Int; f45: Int; f46: Int; f47: Int; f48: Int; f49: Int; f50: Int;
    f51: Int; f52: Int; f53: Int; f54: Int; f55: Int; f56: Int; f57: Int; f58: Int; f59: Int; f60: Int;
    f61: Int; f62: Int; f63: Int; f64: Int; f65: Int; f66: Int; f67: Int; f68: Int; f69: Int; f70: Int;
    f71: Int; f72: Int; f73: Int; f74: Int; f75: Int; f76: Int; f77: Int; f78: Int; f79: Int; f80: Int;
    f81: Int; f82: Int; f83: Int; f84: Int; f85: Int; f86: Int; f87: Int; f88: Int; f89: Int; f90: Int;
    f91: Int; f92: Int; f93: Int; f94: Int; f95: Int; f96: Int; f97: Int; f98: Int; f99: Int; f100: Int;

    init() {
        self.f01=1; self.f02=2; self.f03=3; self.f04=4; self.f05=5; self.f06=6; self.f07=7; self.f08=8; self.f09=9; self.f10=10;
        self.f11=11; self.f12=12; self.f13=13; self.f14=14; self.f15=15; self.f16=16; self.f17=17; self.f18=18; self.f19=19; self.f20=20;
        self.f21=21; self.f22=22; self.f23=23; self.f24=24; self.f25=25; self.f26=26; self.f27=27; self.f28=28; self.f29=29; self.f30=30;
        self.f31=31; self.f32=32; self.f33=33; self.f34=34; self.f35=35; self.f36=36; self.f37=37; self.f38=38; self.f39=39; self.f40=40;
        self.f41=41; self.f42=42; self.f43=43; self.f44=44; self.f45=45; self.f46=46; self.f47=47; self.f48=48; self.f49=49; self.f50=50;
        self.f51=51; self.f52=52; self.f53=53; self.f54=54; self.f55=55; self.f56=56; self.f57=57; self.f58=58; self.f59=59; self.f60=60;
        self.f61=61; self.f62=62; self.f63=63; self.f64=64; self.f65=65; self.f66=66; self.f67=67; self.f68=68; self.f69=69; self.f70=70;
        self.f71=71; self.f72=72; self.f73=73; self.f74=74; self.f75=75; self.f76=76; self.f77=77; self.f78=78; self.f79=79; self.f80=80;
        self.f81=81; self.f82=82; self.f83=83; self.f84=84; self.f85=85; self.f86=86; self.f87=87; self.f88=88; self.f89=89; self.f90=90;
        self.f91=91; self.f92=92; self.f93=93; self.f94=94; self.f95=95; self.f96=96; self.f97=97; self.f98=98; self.f99=99; self.f100=100;
    }
}