contract ManyBools {
  b1: Bool = true;
  b2: Bool = false;
  b3: Bool = true;
  b4: Bool = false;
  b5: Bool = true;
  b6: Bool = false;
  b7: Bool = true;
  b8: Bool = false;
  b9: Bool = true;
  b10: Bool = false;
  b11: Bool = true;
  b12: Bool = false;
  b13: Bool = true;
  b14: Bool = false;
  b15: Bool = true;
  b16: Bool = false;
  b17: Bool = true;
  b18: Bool = false;
  b19: Bool = true;
  b20: Bool = false;

  init() {}
}