contract ManyOptionals {
    o1: Int?;
    o2: Int?;
    o3: Int?;
    o4: Int?;
    o5: Int?;
    o6: Bool?;
    o7: Bool?;
    o8: Bool?;
    o9: Bool?;
    o10: Bool?;

    init() {
        self.o1 = null;
        self.o2 = null;
        self.o3 = null;
        self.o4 = null;
        self.o5 = null;
        self.o6 = null;
        self.o7 = null;
        self.o8 = null;
        self.o9 = null;
        self.o10 = null;
    }
}