contract TestContract {
    f1: Int as uint8 = 1;
    f2: Int as uint8 = 2;
    f3: Int as uint8 = 3;
    f4: Int as uint8 = 4;
    f5: Int as uint8 = 5;
    f6: Int as uint8 = 6;
    f7: Int as uint8 = 7;
    f8: Int as uint8 = 8;
    f9: Int as uint8 = 9;
    f10: Int as uint8 = 10;
    f11: Int as uint8 = 11;
    f12: Int as uint8 = 12;

    init() {
        self.f1 = 101;
        self.f2 = 102;
        self.f3 = 103;
        self.f4 = 104;
        self.f5 = 105;
        self.f6 = 106;
        self.f7 = 107;
        self.f8 = 108;
        self.f9 = 109;
        self.f10 = 110;
        self.f11 = 111;
        self.f12 = 112;
    }
}