contract TestContract {
    o1: Int?;
    o2: Bool?;
    o3: String?;
    o4: Int?;
    o5: Bool?;
    o6: String?;
    o7: Int?;
    o8: Bool?;
    o9: String?;
    o10: Int?;
    o11: Bool?;
    o12: String?;
    o13: Int?;
    o14: Bool?;
    o15: String?;

    init() {
        self.o1 = 1;
        self.o2 = true;
        self.o3 = "a";
        self.o4 = 4;
        self.o5 = false;
        self.o6 = "b";
        self.o7 = 7;
        self.o8 = true;
        self.o9 = "c";
        self.o10 = 10;
        self.o11 = false;
        self.o12 = "d";
        self.o13 = 13;
        self.o14 = true;
        self.o15 = "e";
    }
}