contract OptionalDeepTree {
    child1: Int?;
    child2: Int?;
    child3: Int?;
    child4: Int?;
    child5: Int?;
    child6: Int?;
    child7: Int?;
    child8: Int?;
    child9: Int?;
    child10: Int?;

    init() {
        self.child1 = null;
        self.child2 = null;
        self.child3 = null;
        self.child4 = null;
        self.child5 = null;
        self.child6 = null;
        self.child7 = null;
        self.child8 = null;
        self.child9 = null;
        self.child10 = null;
    }
}
