contract TestContract {
    a: Int;
    b: Int?;
    c: Bool;
    d: Bool?;
    e: String;
    f: String?;
    g: Int;
    h: Int?;
    i: Bool;
    j: Bool?;

    init() {
        self.a = 1;
        self.b = null;
        self.c = true;
        self.d = false;
        self.e = "abc";
        self.f = null;
        self.g = 7;
        self.h = 8;
        self.i = false;
        self.j = null;
    }
}