contract OptionalCombinations {
    opt1: Int?;
    opt2: Bool?;
    opt3: String?;
    opt4: Cell?;
    opt5: Address?;
    opt6: Int?;
    opt7: Bool?;
    opt8: String?;

    init() {
        self.opt1 = null;
        self.opt2 = null;
        self.opt3 = null;
        self.opt4 = null;
        self.opt5 = null;
        self.opt6 = null;
        self.opt7 = null;
        self.opt8 = null;
    }
}
