contract UltraHugeState {
    i1: Int; i2: Int; i3: Int; i4: Int; i5: Int;
    i6: Int; i7: Int; i8: Int; i9: Int; i10: Int;
    i11: Int; i12: Int; i13: Int; i14: Int; i15: Int;
    i16: Int; i17: Int; i18: Int; i19: Int; i20: Int;
    i21: Int; i22: Int; i23: Int; i24: Int; i25: Int;
    i26: Int; i27: Int; i28: Int; i29: Int; i30: Int;
    b1: Bool; b2: Bool; b3: Bool; b4: Bool; b5: Bool;
    b6: Bool; b7: Bool; b8: Bool; b9: Bool; b10: Bool;
    b11: Bool; b12: Bool; b13: Bool; b14: Bool; b15: Bool;
    b16: Bool; b17: Bool; b18: Bool; b19: Bool; b20: Bool;

    init() {
        self.i1=1; self.i2=2; self.i3=3; self.i4=4; self.i5=5;
        self.i6=6; self.i7=7; self.i8=8; self.i9=9; self.i10=10;
        self.i11=11; self.i12=12; self.i13=13; self.i14=14; self.i15=15;
        self.i16=16; self.i17=17; self.i18=18; self.i19=19; self.i20=20;
        self.i21=21; self.i22=22; self.i23=23; self.i24=24; self.i25=25;
        self.i26=26; self.i27=27; self.i28=28; self.i29=29; self.i30=30;
        self.b1=true; self.b2=false; self.b3=true; self.b4=false; self.b5=true;
        self.b6=false; self.b7=true; self.b8=false; self.b9=true; self.b10=false;
        self.b11=true; self.b12=false; self.b13=true; self.b14=false; self.b15=true;
        self.b16=false; self.b17=true; self.b18=false; self.b19=true; self.b20=false;
    }
}