contract BigOptionals {
    a: Int?;
    b: Int?;
    c: Int?;
    d: Int?;
    e: Int?;
    f: Int?;
    g: Int?;
    h: Int?;
    i: Int?;
    j: Int?;
    k: Int?;
    l: Int?;
    m: Int?;
    n: Int?;
    o: Int?;
    p: Int?;
    q: Int?;
    r: Int?;
    s: Int?;
    t: Int?;

    init() {
        self.a=1; self.b=null; self.c=2; self.d=null; self.e=3;
        self.f=null; self.g=4; self.h=null; self.i=5; self.j=null;
        self.k=6; self.l=null; self.m=7; self.n=null; self.o=8;
        self.p=null; self.q=9; self.r=null; self.s=10; self.t=null;
    }
}