contract TenFields {
    a: Int = 1;
    b: Bool = false;
    c: Int = 2;
    d: Bool = true;
    e: Int = 3;
    f: Bool = false;
    g: Int = 4;
    h: Bool = true;
    i: Int = 5;
    j: Bool = false;

    init() {
        self.a = 11;
        self.b = true;
        self.c = 12;
        self.d = false;
        self.e = 13;
        self.f = true;
        self.g = 14;
        self.h = false;
        self.i = 15;
        self.j = true;
    }
}
