contract TestContract {
    s1: Int;
    s2: Int?;
    s3: Int;
    s4: Int?;
    s5: Int;
    s6: Int?;
    s7: Int;
    s8: Int?;
    s9: Int;
    s10: Int?;
    s11: Int;

    init() {
        self.s1 = 1;
        self.s2 = null;
        self.s3 = 3;
        self.s4 = 4;
        self.s5 = 5;
        self.s6 = null;
        self.s7 = 7;
        self.s8 = 8;
        self.s9 = 9;
        self.s10 = null;
        self.s11 = 11;
    }
}