contract LargePrimitiveFields {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int;
    f5: Bool;
    f6: String;
    f7: Bool?;
    f8: String?;
    f9: Int?;
    f10: Int;
    f11: Bool;
    f12: String;
    f13: Int;
    f14: Bool;
    f15: String;
    f16: Bool?;
    f17: String?;
    f18: Int?;
    f19: Int;
    f20: Bool;

    init() {
        self.f1 = 1;
        self.f2 = true;
        self.f3 = "3";
        self.f4 = 4;
        self.f5 = false;
        self.f6 = "6";
        self.f7 = null;
        self.f8 = null;
        self.f9 = null;
        self.f10 = 10;
        self.f11 = true;
        self.f12 = "12";
        self.f13 = 13;
        self.f14 = false;
        self.f15 = "15";
        self.f16 = null;
        self.f17 = null;
        self.f18 = null;
        self.f19 = 19;
        self.f20 = true;
    }
}
