contract LongFieldList {
    a0: Int = 0; b0: Bool = false;
    a1: Int = 1; b1: Bool = true;
    a2: Int = 2; b2: Bool = false;
    a3: Int = 3; b3: Bool = true;
    a4: Int = 4; b4: Bool = false;
    a5: Int = 5; b5: Bool = true;
    a6: Int = 6; b6: Bool = false;
    a7: Int = 7; b7: Bool = true;
    a8: Int = 8; b8: Bool = false;
    a9: Int = 9; b9: Bool = true;

    init() {
        self.a0 = 100;
        self.b0 = true;
    }
}
