contract ManyPrimitives {
    i1: Int;
    i2: Int;
    b1: Bool;
    b2: Bool;
    s1: String;
    s2: String;
    oi1: Int?;
    oi2: Int?;
    ob1: Bool?;
    ob2: Bool?;
    os1: String?;
    os2: String?;

    init() {
        self.i1 = 1;
        self.i2 = 2;
        self.b1 = true;
        self.b2 = false;
        self.s1 = "a";
        self.s2 = "b";
        self.oi1 = null;
        self.oi2 = null;
        self.ob1 = null;
        self.ob2 = null;
        self.os1 = null;
        self.os2 = null;
    }
}