contract ManyFields {
    a1: Int;
    a2: Bool;
    a3: String;
    a4: Int?;
    a5: Bool;
    a6: String;
    a7: Int;
    a8: Bool;
    a9: String;
    a10: Int?;

    init() {
        self.a1 = 0;
        self.a2 = true;
        self.a3 = "x";
        self.a4 = null;
        self.a5 = false;
        self.a6 = "y";
        self.a7 = 42;
        self.a8 = true;
        self.a9 = "z";
        self.a10 = null;
    }
}