contract WideOptionalBools {
    b1: Bool?; b2: Bool?; b3: Bool?; b4: Bool?; b5: Bool?;
    b6: Bool?; b7: Bool?; b8: Bool?; b9: Bool?; b10: Bool?;
    b11: Bool?; b12: Bool?; b13: Bool?; b14: Bool?; b15: Bool?;

    init() {
        self.b1=null; self.b2=null; self.b3=null; self.b4=null; self.b5=null;
        self.b6=null; self.b7=null; self.b8=null; self.b9=null; self.b10=null;
        self.b11=null; self.b12=null; self.b13=null; self.b14=null; self.b15=null;
    }
}