contract BigVars {
    x0: Int; x1: Int; x2: Int; x3: Int; x4: Int;
    x5: Int; x6: Int; x7: Int; x8: Int; x9: Int;
    x10: Int; x11: Int; x12: Int; x13: Int; x14: Int;
    x15: Int; x16: Int; x17: Int; x18: Int; x19: Int;
    x20: Int; x21: Int; x22: Int; x23: Int; x24: Int;
    x25: Int; x26: Int; x27: Int; x28: Int; x29: Int;
    x30: Int; x31: Int; x32: Int; x33: Int; x34: Int;
    x35: Int; x36: Int; x37: Int; x38: Int; x39: Int;
    
    init() {
      self.x0=0; self.x1=1; self.x2=2; self.x3=3; self.x4=4;
      self.x5=5; self.x6=6; self.x7=7; self.x8=8; self.x9=9;
      self.x10=10; self.x11=11; self.x12=12; self.x13=13; self.x14=14;
      self.x15=15; self.x16=16; self.x17=17; self.x18=18; self.x19=19;
      self.x20=20; self.x21=21; self.x22=22; self.x23=23; self.x24=24;
      self.x25=25; self.x26=26; self.x27=27; self.x28=28; self.x29=29;
      self.x30=30; self.x31=31; self.x32=32; self.x33=33; self.x34=34;
      self.x35=35; self.x36=36; self.x37=37; self.x38=38; self.x39=39;
    }
}