contract TestContract {
    n1: Int = 1;
    n2: Int = 2;
    n3: Int = 3;
    n4: Int = 4;
    n5: Int = 5;
    n6: Int = 6;
    n7: Int = 7;
    n8: Int = 8;
    n9: Int = 9;
    n10: Int = 10;
    
    init() {
        self.n1 = 11;
        self.n2 = 12;
        self.n3 = 13;
        self.n4 = 14;
        self.n5 = 15;
        self.n6 = 16;
        self.n7 = 17;
        self.n8 = 18;
        self.n9 = 19;
        self.n10 = 20;
    }
    receive(){}
}