contract LargeFieldList {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int?;
    f5: Bool;
    f6: Int;
    f7: String;
    f8: Int?;
    f9: Bool;
    f10: Int;
    f11: String;
    f12: Int?;
    f13: Bool;
    f14: Int;
    f15: String;
    f16: Int?;

    init() {
        self.f1 = 1;
        self.f2 = false;
        self.f3 = "a";
        self.f4 = null;
        self.f5 = true;
        self.f6 = 6;
        self.f7 = "b";
        self.f8 = null;
        self.f9 = true;
        self.f10 = 10;
        self.f11 = "c";
        self.f12 = null;
        self.f13 = false;
        self.f14 = 14;
        self.f15 = "d";
        self.f16 = null;
    }
}
