contract ManyOptionalFields {
    a: Int?;
    b: Bool?;
    c: Cell?;
    d: Slice?;
    e: Address?;
    f: String?;
    g: Int?;
    h: Bool?;
    i: Cell?;
    j: Slice?;
    k: Address?;
    l: String?;

    init() {
        self.a=null;self.b=null;self.c=null;self.d=null;self.e=null;
        self.f=null;self.g=null;self.h=null;self.i=null;self.j=null;
        self.k=null;self.l=null;
    }
}