contract LongOptPrimitives {
    a: Int?; b: Int?; c: Int?; d: Int?; e: Int?;
    f: Bool?; g: Bool?; h: Bool?; i: Bool?; j: Bool?;
    k: String?; l: String?; m: String?; n: String?; o: String?;

    init() {
        self.a = null; self.b = 1; self.c = null; self.d = 2; self.e = null;
        self.f = true; self.g = null; self.h = false; self.i = null; self.j = true;
        self.k = "a"; self.l = null; self.m = "c"; self.n = null; self.o = "e";
    }
}