// Contract with atypically long parameter list
contract LongParams {
    a: Int = 1;
    b: Int = 2;
    c: Int = 3;
    d: Int = 4;
    e: Int = 5;
    f: Int = 6;
    g: Int = 7;
    h: Int = 8;
    i: Int = 9;
    j: Int = 10;
    k: Int = 11;
    l: Int = 12;
    m: Int = 13;
    n: Int = 14;
    o: Int = 15;

    init() {
        self.a=10; self.b=11; self.c=12; self.d=13; self.e=14;
        self.f=15; self.g=16; self.h=17; self.i=18; self.j=19;
        self.k=20; self.l=21; self.m=22; self.n=23; self.o=24;
    }
}