contract BigFlat {
    a: Int; b: Int; c: Int; d: Int; e: Int;
    f: Bool; g: Bool; h: Bool; i: Bool; j: Bool;
    k: String; l: String; m: String; n: String; o: String;
    p: Int?; q: Bool?; r: String?; s: Int?; t: Bool?;
    u: String?; v: Int; w: Bool; x: String; y: Int?;

    init() {
        self.a=1; self.b=2; self.c=3; self.d=4; self.e=5;
        self.f=true; self.g=false; self.h=true; self.i=false; self.j=true;
        self.k="k"; self.l="l"; self.m="m"; self.n="n"; self.o="o";
        self.p=10; self.q=null; self.r="r"; self.s=null; self.t=false;
        self.u=null; self.v=6; self.w=true; self.x="x"; self.y=99;
    }
}