contract ManyFields {
    f0: Int;
    f1: Int;
    f2: Int;
    f3: Int;
    f4: Int;
    f5: Int;
    f6: Int;
    f7: Int;
    f8: Int;
    f9: Int;
    f10: Int;
    f11: Int;
    f12: Int;
    f13: Int;
    f14: Int;

    init() {
        self.f0=1; self.f1=2; self.f2=3; self.f3=4; self.f4=5;
        self.f5=6; self.f6=7; self.f7=8; self.f8=9; self.f9=10;
        self.f10=11; self.f11=12; self.f12=13; self.f13=14; self.f14=15;
    }
}