contract LongList {
    f1: Int;
    f2: Int;
    f3: Bool;
    f4: Int?;
    f5: Bool?;
    f6: Int;
    f7: Bool;
    f8: Bool?;
    f9: Int?;
    f10: Int;
    
    init() {
        self.f1 = 1;
        self.f2 = 2;
        self.f3 = true;
        self.f4 = null;
        self.f5 = null;
        self.f6 = 6;
        self.f7 = false;
        self.f8 = null;
        self.f9 = null;
        self.f10 = 10;
    }
}