contract BigStorage {
 a: Int;
 b: Bool;
 c: String;
 d: Int?;
 e: String?;
 f: Bool?;
 g: Int;
 h: Bool;
 i: String;
 j: Int?;
 k: Bool?;
 l: String?;
 m: Int;
 n: Bool;
 o: String;

 init() {
  self.a = 1; self.b = true; self.c = "1";
  self.d = null; self.e = "2"; self.f = false;
  self.g = 3; self.h = false; self.i = "3";
  self.j = 4; self.k = null; self.l = null;
  self.m = 5; self.n = true; self.o = "end";
 }
}