contract LargeFieldList {
    field1: Int;
    field2: Bool;
    field3: Int;
    field4: String;
    field5: Bool;
    field6: Int;
    field7: String;
    field8: Bool;
    field9: Int;
    field10: String;
    
    init() {
        self.field1 = 1;
        self.field2 = true;
        self.field3 = 3;
        self.field4 = "four";
        self.field5 = false;
        self.field6 = 6;
        self.field7 = "seven";
        self.field8 = true;
        self.field9 = 9;
        self.field10 = "ten";
    }
}