contract TestLongBools {
    b1: Bool;
    b2: Bool;
    b3: Bool;
    b4: Bool;
    b5: Bool;
    b6: Bool;
    b7: Bool;
    b8: Bool;
    b9: Bool;
    b10: Bool;
    b11: Bool;
    b12: Bool;
    b13: Bool;
    b14: Bool;
    b15: Bool;
    b16: Bool;
    b17: Bool;
    b18: Bool;
    b19: Bool;
    b20: Bool;
    b21: Bool;
    b22: Bool;
    b23: Bool;
    b24: Bool;
    b25: Bool;
    b26: Bool;
    b27: Bool;
    b28: Bool;
    b29: Bool;
    b30: Bool;

    init() {
        self.b1=true; self.b2=true; self.b3=true; self.b4=true; self.b5=true;
        self.b6=true; self.b7=true; self.b8=true; self.b9=true; self.b10=true;
        self.b11=true; self.b12=true; self.b13=true; self.b14=true; self.b15=true;
        self.b16=true; self.b17=true; self.b18=true; self.b19=true; self.b20=true;
        self.b21=true; self.b22=true; self.b23=true; self.b24=true; self.b25=true;
        self.b26=true; self.b27=true; self.b28=true; self.b29=true; self.b30=true;
    }
}