contract HugeFlatStorage {
    a1: Int; a2: Int; a3: Int; a4: Int; a5: Int; a6: Int; a7: Int; a8: Int; a9: Int; a10: Int;
    b1: Bool; b2: Bool; b3: Bool; b4: Bool; b5: Bool; b6: Bool; b7: Bool; b8: Bool; b9: Bool; b10: Bool;

    init() {
        self.a1 = 1; self.a2 = 2; self.a3 = 3; self.a4 = 4; self.a5 = 5; self.a6 = 6;
        self.a7 = 7; self.a8 = 8; self.a9 = 9; self.a10 = 10;
        self.b1 = true; self.b2 = false; self.b3 = true; self.b4 = false; self.b5 = true;
        self.b6 = false; self.b7 = true; self.b8 = false; self.b9 = true; self.b10 = false;
    }
}
