contract ManyVars {
    i1: Int;
    i2: Int;
    i3: Int;
    i4: Int;
    i5: Int;
    i6: Int;
    b1: Bool;
    b2: Bool;
    s1: String;
    s2: String;

    init() {
        self.i1 = 1;
        self.i2 = 2;
        self.i3 = 3;
        self.i4 = 4;
        self.i5 = 5;
        self.i6 = 6;
        self.b1 = false;
        self.b2 = true;
        self.s1 = "a";
        self.s2 = "b";
    }
}
