contract TooManyFields {
    a1: Int; a2: Int; a3: Int; a4: Int; a5: Int;
    a6: Int; a7: Int; a8: Int; a9: Int; a10: Int;
    a11: Int; a12: Int; a13: Int; a14: Int; a15: Int;
    a16: Int; a17: Int; a18: Int; a19: Int; a20: Int;
    a21: Int; a22: Int; a23: Int; a24: Int; a25: Int;
    a26: Int; a27: Int; a28: Int; a29: Int; a30: Int;
    a31: Int; a32: Int; a33: Int; a34: Int; a35: Int;
    a36: Int; a37: Int; a38: Int; a39: Int; a40: Int;
    a41: Int; a42: Int; a43: Int; a44: Int; a45: Int;
    a46: Int; a47: Int; a48: Int; a49: Int; a50: Int;

    init() {
        self.a1=1; self.a2=2; self.a3=3; self.a4=4; self.a5=5;
        self.a6=6; self.a7=7; self.a8=8; self.a9=9; self.a10=10;
        self.a11=11; self.a12=12; self.a13=13; self.a14=14; self.a15=15;
        self.a16=16; self.a17=17; self.a18=18; self.a19=19; self.a20=20;
        self.a21=21; self.a22=22; self.a23=23; self.a24=24; self.a25=25;
        self.a26=26; self.a27=27; self.a28=28; self.a29=29; self.a30=30;
        self.a31=31; self.a32=32; self.a33=33; self.a34=34; self.a35=35;
        self.a36=36; self.a37=37; self.a38=38; self.a39=39; self.a40=40;
        self.a41=41; self.a42=42; self.a43=43; self.a44=44; self.a45=45;
        self.a46=46; self.a47=47; self.a48=48; self.a49=49; self.a50=50;
    }
}