contract LargeOptional {
    opt1: Int? = null;
    opt2: Int? = null;
    opt3: Int? = null;
    opt4: Int? = null;
    opt5: Int? = null;
    opt6: Int? = null;
    opt7: Int? = null;
    opt8: Int? = null;
    opt9: Int? = null;
    opt10: Int? = null;
    opt11: Int? = null;
    opt12: Int? = null;
    opt13: Int? = null;
    opt14: Int? = null;
    opt15: Int? = null;
    opt16: Int? = null;
    opt17: Int? = null;
    opt18: Int? = null;
    opt19: Int? = null;
    opt20: Int? = null;
}