contract LargeNumberOfOptionals {
    a1: Int?;
    a2: Int?;
    a3: Int?;
    a4: Int?;
    a5: Int?;
    a6: Int?;
    a7: Int?;
    a8: Int?;
    a9: Int?;
    a10: Int?;

    init() {
        self.a1 = null;
        self.a2 = null;
        self.a3 = null;
        self.a4 = null;
        self.a5 = null;
        self.a6 = null;
        self.a7 = null;
        self.a8 = null;
        self.a9 = null;
        self.a10 = null;
    }
}
