contract ManyFields {
    f1: Int;
    f2: Bool;
    f3: String;
    f4: Int?;
    f5: Bool?;
    f6: String?;
    f7: Int;
    f8: Bool;
    f9: String;
    f10: Int?;

    init() {
        self.f1 = 1;
        self.f2 = false;
        self.f3 = "a";
        self.f4 = null;
        self.f5 = true;
        self.f6 = null;
        self.f7 = 7;
        self.f8 = true;
        self.f9 = "z";
        self.f10 = 10; 
    }
}