message(0xdeadbeef) message_decl_0 {
    x: Int;
}

message(3735928559) message_decl_1 {
    x: Int;
    y: Int;
}

message(0o33653337357) message_decl_2 {
    x: Int;
    y: Int;
    z: Int;
}

message(0b11011110101011011011111011101111) message_decl_3 {
    x: Int;
    y: Int;
    z: Int;
    w: Int;
}

message message_decl_4 {
    value: Int;
}

message(constant_def_5 + 1) message_decl_6 {
    a: Int;
}

const constant_def_5: Int = 0xdeadbeef;

contract contract_7 {}
